import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=decodeURIComponent(new URL('../',import.meta.url).pathname),p=root+'data/driver_tests/',out=root+'outputs/driver_tests';
const read=async n=>JSON.parse(await fs.readFile(p+n+'.json','utf8'));
const [forecasts,fits,scores,facts]=await Promise.all(['forecasts','fits','scores','pg_quarterly'].map(read));
const sources=JSON.parse(await fs.readFile(root+'data/history_rebuild/selected_source_manifest.json','utf8'));
const extra=await read('added_source_rows');
const w=Workbook.create(),names=['Review','Policy timing','Scores','Forecasts','Model fits','PG facts'];
const sh=Object.fromEntries(names.map(n=>[n,w.worksheets.add(n)]));
const C=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;};
const V=(s,c,v)=>s.getRange(c).values=[[v]],F=(s,c,v)=>s.getRange(c).formulas=[[v]],D=s=>new Date(s+'T00:00:00Z');
const pp='0.00;[Red](0.00);0.00',usd='"$"#,##0.00;[Red]("$"#,##0.00);"$"0.00';
function setup(s,title,widths,rows){s.showGridLines=false;s.getRange(`A1:${C(widths.length+1)}${rows}`).format={font:{name:'Arial',size:12,color:'#17324F'},rowHeight:26,verticalAlignment:'center'};s.getRange(`A1:A${rows}`).format.columnWidth=3;widths.forEach((v,i)=>s.getRange(`${C(i+2)}1:${C(i+2)}${rows}`).format.columnWidth=v);V(s,'B2',title);s.getRange('B2').format.font={size:19,bold:true};if(rows>60)s.freezePanes.freezeRows(5);}
function head(s,n,labels){const r=s.getRange(`B${n}:${C(labels.length+1)}${n}`);r.values=[labels];r.format={fill:'#17324F',font:{bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:48};}
function red(s,r){s.getRange(r).format.font={color:'#C62828',bold:true};s.getRange(r).format.borders={preset:'outside',style:'medium',color:'#C62828'};}
let s=sh['PG facts'];setup(s,'Published P&G segment history',[18,37,20,20,20,18,70],facts.length+6);head(s,5,['Quarter ended','Segment','Pricing contribution pp','Organic volume growth %','Organic sales growth %','Published','Original source']);const fr={};
s.getRange(`B6:H${facts.length+5}`).values=facts.map((r,i)=>{fr[r.segment+'|'+r.period_end]=i+6;return[D(r.period_end),r.segment,r.price_contribution,r.organic_volume_growth,r.organic_sales_growth,D(r.publication_date),sources.find(z=>z.period===r.period_end)?.url??extra.find(z=>z.period_end===r.period_end)?.source_url??extra.find(z=>z.period===r.period_end)?.url??'See added_source_rows.csv'];});s.getRange(`B6:B${facts.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`G6:G${facts.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`D6:F${facts.length+5}`).setNumberFormat(pp);
const mc={price_contribution:'D',organic_volume_growth:'E',organic_sales_growth:'F'};
s=sh['Model fits'];setup(s,'Recalculate model coefficients from historical training totals',[12,56,23,18,20,18,...Array(20).fill(17)],fits.length+6);V(s,'B3','Prepared training totals come from training.csv. To change source history or vintage dates, rerun the analysis.');head(s,5,['Fit ID','P&G measure','Model','Target quarter','Stage','Known by','n','Sum x','Sum z','Sum y','Sum xx','Sum zz','Sum xz','Sum xy','Sum zy','Target x','Target z','Centered xx','Centered zz','Centered xz','Centered xy','Centered zy','Slope x','Slope z','Intercept','Forecast']);
s.getRange(`B6:R${fits.length+5}`).values=fits.map(r=>[r.fit_id,r.pair,r.model,D(r.quarter),r.stage,D(r.cutoff),r.n,r.sum_x,r.sum_z,r.sum_y,r.sum_xx,r.sum_zz,r.sum_xz,r.sum_xy,r.sum_zy,r.target_x,r.target_z]);
s.getRange(`S6:AA${fits.length+5}`).formulas=fits.map((r,i)=>{const n=i+6;return[`=L${n}-I${n}^2/H${n}`,`=M${n}-J${n}^2/H${n}`,`=N${n}-I${n}*J${n}/H${n}`,`=O${n}-I${n}*K${n}/H${n}`,`=P${n}-J${n}*K${n}/H${n}`,r.model==='Own + product'?`=(V${n}*T${n}-W${n}*U${n})/(S${n}*T${n}-U${n}^2)`:`=V${n}/S${n}`,r.model==='Own + product'?`=(W${n}*S${n}-V${n}*U${n})/(S${n}*T${n}-U${n}^2)`:'=0',`=K${n}/H${n}-X${n}*I${n}/H${n}-Y${n}*J${n}/H${n}`,`=Z${n}+X${n}*Q${n}+Y${n}*R${n}`];});s.getRange(`I6:AA${fits.length+5}`).setNumberFormat(pp);for(const c of ['E','G'])s.getRange(`${c}6:${c}${fits.length+5}`).setNumberFormat('dd-mmm-yy');
s=sh.Forecasts;setup(s,'Frozen forecasts and later outcomes',[12,55,18,19,18,23,18,18,18,18,18,18,18,18,18],forecasts.length+6);head(s,5,['ID','P&G measure','Quarter','Stage','Known by','Model','Original prediction','Prior error mean pp','Correction weight','Final forecast','Actual (later)','Error pp','Squared error','Absolute error','Actual published']);
forecasts.forEach((r,i)=>{const n=i+6;s.getRange(`B${n}:G${n}`).values=[[r.id,r.pair,D(r.quarter),r.stage,D(r.cutoff),r.model]];
if(r.fit_id)F(s,'H'+n,`='Model fits'!AA${r.fit_id+5}`);else if(r.base_id)F(s,'H'+n,`=K${r.base_id+5}`);else{const known=facts.filter(f=>f.segment===r.segment&&f.period_end<r.quarter&&f.publication_date<=r.cutoff).sort((a,b)=>a.period_end.localeCompare(b.period_end));const refs=known.slice(r.model==='Last actual'?-1:-4).map(f=>`'PG facts'!${mc[r.metric]}${fr[f.segment+'|'+f.period_end]}`);F(s,'H'+n,`=AVERAGE(${refs.join(',')})`);}
F(s,'I'+n,r.calibration_ids?`=AVERAGE(${r.calibration_ids.split(',').map(k=>'M'+(+k+5)).join(',')})`:'=0');V(s,'J'+n,r.correction_weight);F(s,'K'+n,`=H${n}-I${n}*J${n}`);F(s,'L'+n,`='PG facts'!${mc[r.metric]}${fr[r.segment+'|'+r.quarter]}`);F(s,'M'+n,`=K${n}-L${n}`);F(s,'N'+n,`=M${n}^2`);F(s,'O'+n,`=ABS(M${n})`);V(s,'P'+n,D(r.actual_publication));});for(const c of ['D','F','P'])s.getRange(`${c}6:${c}${forecasts.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`H6:O${forecasts.length+5}`).setNumberFormat(pp);
s=sh.Scores;setup(s,'Compare methods on identical target quarters',[56,20,23,19,14,18,18,18,18,18],scores.length+6);head(s,5,['P&G measure','Stage','Model','Sample','Quarters','RMSE pp','MAE pp','Bias pp','Last actual RMSE','Broad market RMSE']);
scores.forEach((r,i)=>{const n=i+6,ids=r.forecast_ids.split(',').map(Number),refs=c=>ids.map(k=>`Forecasts!${c}${k+5}`).join(',');s.getRange(`B${n}:F${n}`).values=[[r.pair,r.stage,r.model,r.sample,r.quarters]];const br=m=>ids.map(k=>{const z=forecasts[k-1];return'Forecasts!N'+(forecasts.find(v=>v.pair===z.pair&&v.quarter===z.quarter&&v.stage===z.stage&&v.model===m).id+5);}).join(',');s.getRange(`G${n}:K${n}`).formulas=[[`=SQRT(AVERAGE(${refs('N')}))`,`=AVERAGE(${refs('O')})`,`=AVERAGE(${refs('M')})`,`=SQRT(AVERAGE(${br('Last actual')}))`,`=SQRT(AVERAGE(${br('Broad market')}))`]];});s.getRange(`G6:K${scores.length+5}`).setNumberFormat(pp);
s=sh.Review;setup(s,'P&G | Which model changes helped?',[31,22,22,22,22],36);V(s,'B3','21 company quarters · 12 test quarters · 3 forecast checkpoints per quarter');head(s,5,['Pricing contribution','Broad model','Bias corrected','Last 8 training qtrs','Last actual']);
for(const [i,seg] of ['Beauty','Grooming'].entries()){const n=i+6;V(s,'B'+n,seg);['Broad market','Bias correction','Broad rolling 8','Last actual'].forEach((m,j)=>{const ix=scores.findIndex(r=>r.pair===seg+' / price_contribution'&&r.stage==='Pre-earnings'&&r.sample==='Recent eight'&&r.model===m);F(s,C(j+3)+n,`=Scores!G${ix+6}`);});}s.getRange('C6:F7').setNumberFormat(pp);red(s,'C6:E7');
V(s,'B9','RMSE in percentage points. Lower is better. Same eight quarters: Apr 2024–Mar 2026.');V(s,'B11','Beauty: correction helped; a shorter training window helped more in this sample.');V(s,'B12','Grooming: both changes worsened the broad model.');V(s,'B14','A finer product index did not improve Beauty: 1.79pp versus 1.43pp.');V(s,'B15','One-quarter lags also worsened both pricing models on the same seven quarters.');V(s,'B17','Retrospective development: these results do not establish future accuracy.');V(s,'B18','Policy timing is a cost sensitivity, not a fitted sales coefficient.');
head(s,21,['Scope','Included','Decision']);s.getRange('B22:D25').values=[['Product price','US cosmetics CPI','Tested; not selected'],['Company history','Own lagged result','Tested as challenger'],['Policy / tariffs','Timing + cost lag','Separate cost build'],['FX / input costs','No matched exposure','Keep as research inputs']];s.getRange('B22:D25').format.wrapText=true;s.getRange('B22:D25').format.rowHeight=45;
s=sh['Policy timing'];setup(s,'Tariffs | Timing changes the quarterly cost',[38,22,23,23,25],53);V(s,'B3','Illustration only: $100m eligible imports and a 10pp incremental duty are NOT P&G facts.');head(s,5,['Editable assumptions','Value','Definition']);const inputs=[['Quarter start',D('2026-04-01'),'Forecast quarter'],['Quarter end',D('2026-06-30'),'Forecast quarter'],['Information cutoff',D('2026-05-15'),'Exclude later announcements'],['Announcement date',D('2026-04-01'),'Hypothetical, known at cutoff'],['Effective date',D('2026-04-28'),'Edit to test earlier / later'],['Quarter eligible imports ($m)',100,'Assumed uniform daily imports'],['Incremental duty rate',.10,'Change versus embedded baseline'],['Inventory / COGS lag (days)',30,'Fixed assumed recognition lag']];s.getRange('B6:D13').values=inputs;s.getRange('C6:C13').format.font={color:'#0000FF'};// Single editable cost build.
s.getRange('D6:D13').format.wrapText=true;s.getRange('D6:D13').format.columnWidth=42;s.getRange('B6:F13').format.rowHeight=34;s.getRange('C6:C10').setNumberFormat('dd-mmm-yy');s.getRange('C11').setNumberFormat(usd);s.getRange('C12').setNumberFormat('0.0%');
head(s,16,['Calculation','Result','How it works']);V(s,'B17','Quarter days');F(s,'C17','=C7-C6+1');V(s,'B18','Policy known by cutoff?');F(s,'C18','=IF(C9<=C8,"Yes","No")');V(s,'B19','Days with incremental duty');F(s,'C19','=IF(C18="Yes",MAX(0,C7-MAX(C6,C10)+1),0)');V(s,'B20','Days reaching COGS this quarter');F(s,'C20','=IF(C18="Yes",MAX(0,C7-MAX(C6,C10)-C13+1),0)');V(s,'B21','Additional import duty ($m)');F(s,'C21','=IF(COUNT(C11:C13)<3,"Missing input",IF(C18="Yes",C11*C12*C19/C17,"Not known at cutoff"))');V(s,'B22','Additional COGS ($m)');F(s,'C22','=IF(COUNT(C11:C13)<3,"Missing input",IF(C18="Yes",C11*C12*C20/C17,"Not known at cutoff"))');V(s,'B23','Pre-tax profit change ($m)');F(s,'C23','=IF(ISNUMBER(C22),-C22,C22)');s.getRange('C21:C23').setNumberFormat(usd);red(s,'C19:C23');V(s,'D21','Imports × incremental rate × day share');V(s,'D22','Same build, after inventory lag');V(s,'D23','Before pricing or other offsets');
V(s,'B26','Timing alone does not identify P&G exposure, exemptions, or inventory turnover.');V(s,'B27','Cash duties and COGS differ. This model has no pre-quarter inventory carry-in.');
head(s,30,['Published P&G evidence','Value','Treatment']);s.getRange('B31:D33').values=[['FY2026 tariff cost ($m, after tax)',400,'Already in company guidance'],['Jan–Mar gross-margin drag (bps)',50,'Actual quarter; not a future rate'],['Potential IEEPA recovery ($m)',200,'No recovery recognized at 31 March']];s.getRange('C31').setNumberFormat(usd);s.getRange('C33').setNumberFormat(usd);s.getRange('D31:D33').format.wrapText=true;s.getRange('B31:F33').format.rowHeight=42;red(s,'C31:C33');
V(s,'B35','Do not subtract the $400m again. Do not divide it by four without support.');V(s,'B36','A possible refund is not booked profit or cash received.');V(s,'B39','Sources / assumptions');V(s,'B40','P&G 24-Apr-2026 release: outlook and January–March margin discussion');V(s,'B41','https://www.sec.gov/Archives/edgar/data/80424/000008042426000056/fy2526q3jfm8-kexhibit991.htm');V(s,'B43','P&G March 2026 10-Q: US Tariffs note; approximately $200m potential recovery');V(s,'B44','https://www.sec.gov/Archives/edgar/data/80424/000008042426000060/pg-20260331.htm');V(s,'B46','Timing example: 12-May-2025 announcement, 14-May effective. Historical rule only.');V(s,'B47','https://www.whitehouse.gov/presidential-actions/2025/05/modifying-reciprocal-tariff-rates-to-reflect-discussions-with-the-peoples-republic-of-china/');V(s,'B49','Rows 6–13: analyst assumptions. Incremental rate is relative to the baseline already modelled.');
w.recalculate();
function close(a,b,label){if(typeof a!=='number'||Math.abs(a-b)>1e-7)throw Error(label+': '+a+' != '+b);}
forecasts.forEach((r,i)=>close(sh.Forecasts.getRange('K'+(i+6)).values[0][0],r.prediction,'Forecast '+r.id));scores.forEach((r,i)=>close(sh.Scores.getRange('G'+(i+6)).values[0][0],r.rmse,'Score '+i));
const pol=sh['Policy timing'];close(pol.getRange('C22').values[0][0],100*.1*34/91,'Early policy');V(pol,'C10',D('2026-06-04'));w.recalculate();close(pol.getRange('C21').values[0][0],100*.1*27/91,'Late duty');close(pol.getRange('C22').values[0][0],0,'Late COGS');V(pol,'C10',D('2026-07-01'));w.recalculate();close(pol.getRange('C21').values[0][0],0,'After quarter');V(pol,'C10',D('2026-04-28'));V(pol,'C11',null);w.recalculate();if(pol.getRange('C22').values[0][0]!=='Missing input')throw Error('Blank exposure');V(pol,'C11',0);w.recalculate();close(pol.getRange('C22').values[0][0],0,'Zero exposure');V(pol,'C11',100);V(pol,'C9',D('2026-06-01'));w.recalculate();if(pol.getRange('C22').values[0][0]!=='Not known at cutoff')throw Error('Future announcement');V(pol,'C9',D('2026-04-01'));w.recalculate();
console.log((await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#N/A',options:{useRegex:true,maxResults:10}})).ndjson);
await fs.mkdir(out,{recursive:true});for(const n of names){const end={Review:'F25','Policy timing':'F27',Scores:'K12',Forecasts:'P12','Model fits':'K12','PG facts':'G12'}[n];await fs.writeFile(out+'/'+n.replaceAll(' ','_')+'.png',new Uint8Array(await(await w.render({sheetName:n,range:'B2:'+end,scale:1.2})).arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(w)).save(out+'/PG_6_Driver_and_Policy_Tests.xlsx');await fs.writeFile(out+'/validation.json',JSON.stringify({all_2992_forecasts_match_python:true,all_scores_match_python:true,policy_early_late_after_quarter_checked:true,policy_missing_zero_and_announcement_guards_checked:true,inputs_restored:true},null,2));console.log('PG_6 workbook saved');
