import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=decodeURIComponent(new URL('../',import.meta.url).pathname),p=root+'data/two_stage/',out=root+'outputs/two_stage';
const read=async n=>JSON.parse(await fs.readFile(p+n+'.json','utf8'));
const [rels,screen,monthly,company,ms,cs,ex]=await Promise.all(['relationship_tests','relationship_scores','monthly_forecasts','company_forecasts','monthly_scores','company_scores','worked_example'].map(read));
const w=Workbook.create(),names=['Review','Worked example','Relationships','Monthly tests','Company tests','Scores'],sh=Object.fromEntries(names.map(n=>[n,w.worksheets.add(n)]));
const C=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;},V=(s,c,v)=>s.getRange(c).values=[[v]],F=(s,c,v)=>s.getRange(c).formulas=[[v]],fmt='0.000;[Red](0.000);0.000';
function setup(s,title,widths,rows){s.showGridLines=false;s.getRange(`A1:${C(widths.length+1)}${rows}`).format={font:{name:'Arial',size:12,color:'#17324F'},rowHeight:27,verticalAlignment:'center'};s.getRange(`A1:A${rows}`).format.columnWidth=3;widths.forEach((v,i)=>s.getRange(`${C(i+2)}1:${C(i+2)}${rows}`).format.columnWidth=v);V(s,'B2',title);s.getRange('B2').format.font={size:20,bold:true};if(rows>60)s.freezePanes.freezeRows(5);}
function head(s,n,labels){const r=s.getRange(`B${n}:${C(labels.length+1)}${n}`);r.values=[labels];r.format={fill:'#17324F',font:{bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:46};}
function red(s,r){s.getRange(r).format.font={color:'#C62828',bold:true};s.getRange(r).format.borders={preset:'outside',style:'medium',color:'#C62828'};}
let s=sh.Relationships;setup(s,'1 | Test the company–market relationship',[59,19,18,20,16,16,16,16,16,16,16,16,16],rels.length+6);V(s,'B3','Conditional screen: Apr 2023–Mar 2024. Market versions fixed at 1 July 2024; not a real-time forecast.');head(s,5,['P&G measure / market series','Window','Quarter','Market version','Training n','Intercept','Slope','Market YoY %','Forecast','PG actual','Last actual','4-quarter mean','Squared error']);
rels.forEach((r,i)=>{const n=i+6;s.getRange(`B${n}:I${n}`).values=[[r.pair,r.window,r.quarter,r.market_vintage,r.n,r.intercept,r.beta,r.market_growth]];F(s,'J'+n,`=G${n}+H${n}*I${n}`);s.getRange(`K${n}:M${n}`).values=[[r.actual,r.last,r.four_mean]];F(s,'N'+n,`=(J${n}-K${n})^2`);});s.getRange(`G6:N${rels.length+5}`).setNumberFormat(fmt);
s=sh['Monthly tests'];setup(s,'2 | Predict only the missing market months',[22,18,19,18,18,26,18,18,18,18,18,16],monthly.length+6);head(s,5,['Series','Target quarter','Checkpoint','Known by','Missing month','Method','Forecast level','Later actual','Truth version','Error %','Absolute error %','Evaluation?']);monthly.forEach((r,i)=>{const n=i+6;s.getRange(`B${n}:J${n}`).values=[[r.series,r.quarter,r.stage,r.cutoff,r.month,r.method,r.predicted_level,r.actual_level,r.truth_vintage]];if(r.actual_level!==null){F(s,'K'+n,`=100*(H${n}/I${n}-1)`);F(s,'L'+n,`=ABS(K${n})`);}V(s,'M'+n,r.evaluation?'Yes':'Calibration');});s.getRange(`H6:I${monthly.length+5}`).setNumberFormat(fmt);s.getRange(`K6:L${monthly.length+5}`).setNumberFormat(fmt);
s=sh['Company tests'];setup(s,'3 | Feed the market estimate into P&G',[59,18,20,18,26,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16],company.length+6);head(s,5,['P&G measure / series','Quarter','Checkpoint','Known by','Method','Training n','Intercept','Slope','Market YoY %','Prediction','Actual','Error pp','Squared error','Last actual','4-qtr mean','Later-filled market %','Later-filled prediction','Relationship error','Missing-input error','Error check']);company.forEach((r,i)=>{const n=i+6;s.getRange(`B${n}:J${n}`).values=[[r.pair,r.quarter,r.stage,r.cutoff,r.method,r.n,r.intercept,r.beta,r.market_growth]];F(s,'K'+n,`=H${n}+I${n}*J${n}`);V(s,'L'+n,r.actual);F(s,'M'+n,`=K${n}-L${n}`);F(s,'N'+n,`=M${n}^2`);s.getRange(`O${n}:Q${n}`).values=[[r.last_actual,r.four_mean,r.perfect_missing_month_growth]];if(r.perfect_missing_month_growth!==null){F(s,'R'+n,`=H${n}+I${n}*Q${n}`);F(s,'S'+n,`=R${n}-L${n}`);F(s,'T'+n,`=K${n}-R${n}`);F(s,'U'+n,`=M${n}-S${n}-T${n}`);}});s.getRange(`H6:U${company.length+5}`).setNumberFormat(fmt);V(s,'B3','Later-filled columns are hindsight diagnostics ONLY. Coefficients are fitted from training_pairs.csv; rerun Python to refit.');
s=sh.Scores;setup(s,'Same-sample accuracy | Lower is better',[60,20,29,16,20,20,20],cs.length+ms.length+screen.length+18);head(s,5,['P&G measure / series','Checkpoint','Method','Quarters','RMSE pp','Last actual RMSE','4-qtr mean RMSE']);cs.forEach((r,i)=>{const n=i+6,ix=company.flatMap((z,k)=>z.pair===r.pair&&z.stage===r.stage&&z.method===r.method?[k+6]:[]);s.getRange(`B${n}:E${n}`).values=[[r.pair,r.stage,r.method,r.quarters]];F(s,'F'+n,`=SQRT(AVERAGE(${ix.map(k=>`'Company tests'!N${k}`).join(',')}))`);V(s,'G'+n,r.last_rmse);V(s,'H'+n,r.mean_rmse);});const mstart=cs.length+9;head(s,mstart,['Market series','Checkpoint','Method','Quarters','MAPE %','Missing months','RMSE %']);ms.forEach((r,i)=>{const n=mstart+i+1,ix=monthly.flatMap((z,k)=>z.series===r.series&&z.stage===r.stage&&z.method===r.method&&z.evaluation&&z.actual_level!==null?[k+6]:[]);s.getRange(`B${n}:E${n}`).values=[[r.series,r.stage,r.method,r.quarters]];F(s,'F'+n,`=AVERAGE(${ix.map(k=>`'Monthly tests'!L${k}`).join(',')})`);V(s,'G'+n,r.missing_month_forecasts);V(s,'H'+n,r.rmse_pct);});const rstart=mstart+ms.length+4;head(s,rstart,['Conditional screen','Window','Selected?','Quarters','RMSE pp','Last actual RMSE','4-qtr mean RMSE']);screen.forEach((r,i)=>{const n=rstart+i+1,ix=rels.flatMap((z,k)=>z.pair===r.pair&&z.window===r.window?[k+6]:[]);s.getRange(`B${n}:E${n}`).values=[[r.pair,r.window,r.selected?'Yes':'No',r.quarters]];F(s,'F'+n,`=SQRT(AVERAGE(${ix.map(k=>`Relationships!N${k}`).join(',')}))`);V(s,'G'+n,r.last_rmse);V(s,'H'+n,r.mean_rmse);});s.getRange(`F6:H${rstart+screen.length}`).setNumberFormat(fmt);
s=sh.Review;setup(s,'P&G | Market relationship → missing month → forecast',[38,24,24,24,24],36);V(s,'B3','21 historical quarters · fixed early screen · 7 later target quarters (availability varies)');head(s,5,['Step','What we tested','Result']);s.getRange('B6:D8').values=[['1. Company–market relationship','11 pairings; 2 windows','6 passed the early screen'],['2. Missing market month','Carry, flat, trend, seasonality','No universal winning method'],['3. P&G forecast','Link both stages; test later data','Better market ≠ better PG']];s.getRange('B6:D8').format.wrapText=true;s.getRange('B6:D8').format.rowHeight=46;
head(s,10,['Two known market months','Model RMSE pp','Last actual pp','4-qtr mean pp','Target quarters']);const selected=cs.filter(r=>r.stage==='Two months'&&r.method==='Available-history choice');selected.forEach((r,i)=>{const n=i+11;V(s,'B'+n,r.pair.split(' | ').slice(0,2).join(' / ').replace('organic_volume_growth','volume').replace('organic_sales_growth','organic sales').replace('price_contribution','pricing'));['F','G','H'].forEach((c,j)=>F(s,C(j+3)+n,`=Scores!${c}${cs.indexOf(r)+6}`));V(s,'F'+n,r.quarters);});s.getRange('B11:B16').format.wrapText=true;s.getRange('B11:F16').format.rowHeight=44;s.getRange('C11:E16').setNumberFormat('0.00');red(s,'C11:E11');
V(s,'B18','Baby / Feminine / Family volume: useful challenger; US-wide demand is an imperfect proxy.');V(s,'B19','Beauty volume and Health Care pricing: last actual wins at this checkpoint.');V(s,'B20','Beauty pricing: small gain here; loses before earnings. Do not use one model at every stage.');
V(s,'B22','Market example: cosmetics CPI seasonal MAPE 0.35% vs carry 0.69% (5 quarters).');V(s,'B23','But Beauty pricing RMSE rises: 1.44pp vs 1.40pp. Open Worked example to see why.');red(s,'B22');
V(s,'B25','Development results, not untouched validation. Small samples; no causal claim.');V(s,'B26','“Available-history choice” uses only earlier verified monthly errors; at least 4 quarters.');V(s,'B27','Versions are preserved checkpoints, not a complete archive of every release day.');V(s,'B29','Reproduce: python3 src/test_two_stage.py; then node src/build_two_stage.mjs');V(s,'B30','Data: data/two_stage/*.csv. Original monthly files: versions_used.csv. Company: pg_quarterly.json.');
s=sh['Worked example'];setup(s,'Beauty pricing | Why a better CPI estimate can still miss P&G',[28,23,23,24,26],55);V(s,'B3','Forecast made with data available by 1 July 2025; target April–June 2025.');head(s,5,['1. Historical June pattern','May CPI','June CPI','June / May']);ex.seasonal.forEach((r,i)=>{const n=i+6;s.getRange(`B${n}:D${n}`).values=[[r.year,r.may,r.june]];F(s,'E'+n,`=D${n}/C${n}`);});s.getRange('C6:D8').setNumberFormat(fmt);s.getRange('E6:E8').setNumberFormat('0.00000');V(s,'B9','Median multiplier');F(s,'E9','=MEDIAN(E6:E8)');s.getRange('E9').setNumberFormat('0.00000');red(s,'E9');
head(s,11,['2. Build quarter CPI','Prior-year CPI','Carry forecast','Seasonal forecast','Actual (known later)']);ex.monthly.forEach((r,i)=>{const n=i+12;s.getRange(`B${n}:D${n}`).values=[[r.month,r.prior_year,r['YoY carry']]];if(r.observed)F(s,'E'+n,`=D${n}`);else F(s,'E'+n,`=E${n-1}*$E$9`);V(s,'F'+n,r.actual);});s.getRange('C12:F14').setNumberFormat(fmt);red(s,'D14:F14');V(s,'B15','Quarter YoY %');for(const c of ['D','E','F'])F(s,c+'15',`=100*(AVERAGE(${c}12:${c}14)/AVERAGE(C12:C14)-1)`);s.getRange('D15:F15').setNumberFormat(fmt);V(s,'B17','April + May are observed. Only June is estimated; later actuals never enter the forecast.');
head(s,19,['3. P&G pricing model','Value','Unit']);V(s,'B20','Fitted intercept');V(s,'C20',ex.company[0].intercept);V(s,'D20','percentage points');V(s,'B21','Fitted slope');V(s,'C21',ex.company[0].beta);V(s,'D21','PG pp / market pp');s.getRange('C20:C21').setNumberFormat(fmt);V(s,'B22','Training quarters');V(s,'C22',ex.company[0].n);V(s,'D22','Jan 2021–Mar 2025');
head(s,24,['4. Compare to P&G','Carry forecast','Seasonal forecast','Later-filled diagnostic']);F(s,'C25','=C20+C21*D15');F(s,'D25','=C20+C21*E15');F(s,'E25','=C20+C21*F15');V(s,'B25','Pricing contribution pp');V(s,'B26','P&G actual pp');s.getRange('C26:E26').values=[[1,1,1]];V(s,'B27','Error pp');for(const c of ['C','D','E'])F(s,c+'27',`=${c}25-${c}26`);s.getRange('C25:E27').setNumberFormat(fmt);red(s,'C25:E27');
V(s,'B29','Even with later June CPI, this relationship predicts 3.15pp; P&G reports 1pp.');V(s,'B30','The lower CPI estimate partly offsets the relationship error. It is not a better model.');
head(s,32,['5. Error explained','Carry','Seasonal']);V(s,'B33','Relationship error pp');F(s,'C33','=E27');F(s,'D33','=E27');V(s,'B34','Missing-month effect pp');F(s,'C34','=C25-E25');F(s,'D34','=D25-E25');V(s,'B35','Total error pp');F(s,'C35','=SUM(C33:C34)');F(s,'D35','=SUM(D33:D34)');s.getRange('C33:D35').setNumberFormat(fmt);
V(s,'B38','Sources: US cosmetics CPI, CUUR0000SEGB02 (not seasonally adjusted).');V(s,'B39','https://alfred.stlouisfed.org/series?seid=CUUR0000SEGB02');V(s,'B40','Forecast vintage: 1 July 2025. June value verified in preserved 28 July 2025 version.');V(s,'B41','This is the earliest version preserved here, not necessarily the first official release.');V(s,'B43','P&G quarter ended 30 June 2025, released 29 July 2025: Beauty pricing +1%.');V(s,'B44','https://www.pginvestor.com/news/news-details/2025/PG-Announces-Fourth-Quarter-and-Fiscal-Year-2025-Results/default.aspx');V(s,'B46','Prepared coefficients use training_pairs.csv, matching the target, stage and series.');V(s,'B47','Input changes recalculate this example. Refit the model by rerunning the analysis.');
w.recalculate();const close=(a,b,l)=>{if(typeof a!=='number'||Math.abs(a-b)>1e-7)throw Error(l+': '+a+' vs '+b);};company.forEach((r,i)=>close(sh['Company tests'].getRange('K'+(i+6)).values[0][0],r.prediction,'prediction'));cs.forEach((r,i)=>close(sh.Scores.getRange('F'+(i+6)).values[0][0],r.rmse,'RMSE'));close(s.getRange('D25').values[0][0],ex.company.find(r=>r.method==='Seasonal step').prediction,'example');const before=s.getRange('D25').values[0][0];V(s,'D13',190);w.recalculate();if(s.getRange('D25').values[0][0]===before)throw Error('Input not linked');V(s,'D13',ex.monthly[1]['YoY carry']);w.recalculate();close(s.getRange('D25').values[0][0],before,'restored');
await fs.mkdir(out,{recursive:true});await fs.writeFile(out+'/formula_check.ndjson',(await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#N/A',options:{useRegex:true,maxResults:10}})).ndjson);await(await SpreadsheetFile.exportXlsx(w)).save(out+'/PG_7_Two_Stage_Forecast.xlsx');await fs.writeFile(out+'/validation.json',JSON.stringify({company_predictions_checked:company.length,company_scores_checked:cs.length,worked_example_checked:true,input_recalculation_checked:true,inputs_restored:true},null,2));console.log('Saved PG_7_Two_Stage_Forecast.xlsx');
