import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=decodeURIComponent(new URL('../',import.meta.url).pathname);
const dir=root+'outputs/april_guidance_sample';
await fs.mkdir(dir,{recursive:true});
const w=Workbook.create();const s=w.worksheets.add('Management guidance');
s.showGridLines=false;
s.getRange('A1:F19').format.font={name:'Arial',size:12,color:'#16324F'};
s.getRange('A1:F19').format.rowHeight=26;
s.getRange('A1:A19').format.columnWidth=3;
s.getRange('B1:B19').format.columnWidth=34;
s.getRange('C1:E19').format.columnWidth=18;
s.getRange('F1:F19').format.columnWidth=4;
s.getRange('B2').values=[['P&G | Management guidance']];
s.getRange('B2').format.font={size:18,bold:true};
s.getRange('B3').values=[['Published 24 Apr 2026 | Full year ending 30 Jun 2026']];
s.getRange('B5:E5').values=[['FY2026 growth vs FY2025','Company low','Midpoint*','Company high']];
s.getRange('B5:E5').format={fill:'#16324F',font:{color:'#FFFFFF',bold:true},rowHeight:32};
s.getRange('B6:E8').values=[['All-in sales',.01,null,.05],['Organic sales',0,null,.04],['Core EPS (non-GAAP)',0,null,.04]];
s.getRange('D6:D8').formulas=[['=(C6+E6)/2'],['=(C7+E7)/2'],['=(C8+E8)/2']];
s.getRange('C6:E8').setNumberFormat('0.0%;(0.0%);0.0%');
s.getRange('B6:E6').format.fill='#FFF0EE';
s.getRange('C6:E6').format.font={color:'#BE2424',bold:true};
s.getRange('C7:C8').format.font.color='#0000FF';s.getRange('E7:E8').format.font.color='#0000FF';
s.getRange('D7:D8').format.font.color='#000000';
s.getRange('B10').values=[['*Midpoint = (low + high) / 2; calculated by us.']];
s.getRange('B11').values=[['The midpoint is not an endorsed management base case.']];
s.getRange('B13').values=[['Important context']];s.getRange('B13').format.font.bold=true;
s.getRange('B14').values=[['P&G said FY2026 EPS was expected toward the lower end.']];
s.getRange('B15').values=[['These annual ranges are not April–June growth forecasts.']];
s.getRange('B17').values=[['Source: P&G Q3 FY2026 release, “Fiscal Year 2026 Guidance”.']];
s.getRange('B18').values=[['https://www.pginvestor.com/news/news-details/2026/PG-Announces-Fiscal-Year-2026-Third-Quarter-Results/default.aspx']];
s.getRange('B18').format.font.size=10;
w.recalculate();
console.log((await w.inspect({kind:'table',range:"'Management guidance'!B5:E8",include:'values,formulas',tableMaxRows:4,tableMaxCols:4})).ndjson);
console.log((await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!',options:{useRegex:true,maxResults:10}})).ndjson);
const img=await w.render({sheetName:s.name,range:'B2:E15',scale:2});
await fs.writeFile(dir+'/guidance_preview.png',new Uint8Array(await img.arrayBuffer()));
await (await SpreadsheetFile.exportXlsx(w)).save(dir+'/PG_1_Management_Guidance.xlsx');
