import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=decodeURIComponent(new URL('../',import.meta.url).pathname),p=root+'data/release_backtest/',out=root+'outputs/release_backtest';
const read=async n=>JSON.parse(await fs.readFile(p+n+'.json','utf8'));
const [pred,train,tm,scored,scores,manifest]=await Promise.all(['predictions','training_pairs','target_months','scored_predictions','scores','vintage_manifest'].map(read));
const facts=JSON.parse(await fs.readFile(root+'data/history_rebuild/pg_quarterly.json','utf8'));
const sources=JSON.parse(await fs.readFile(root+'data/history_rebuild/selected_source_manifest.json','utf8'));
const w=Workbook.create(),names=['Review','Quarter example','Scorecard','Scored quarters','Forecast log','Training pairs','Target months','PG facts','Market sources'];
const sh=Object.fromEntries(names.map(n=>[n,w.worksheets.add(n)]));
const col=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;};
const D=s=>new Date(s+'T00:00:00Z'),V=(s,c,v)=>s.getRange(c).values=[[v]],F=(s,c,v)=>s.getRange(c).formulas=[[v]];
function setup(s,title,widths,n){s.showGridLines=false;const r=s.getRange(`A1:${col(widths.length+1)}${n}`);r.format.font={name:'Arial',size:12,color:'#17324F'};r.format.rowHeight=25;r.format.verticalAlignment='center';s.getRange(`A1:A${n}`).format.columnWidth=3;widths.forEach((x,i)=>s.getRange(`${col(i+2)}1:${col(i+2)}${n}`).format.columnWidth=x);V(s,'B2',title);s.getRange('B2').format.font={size:18,bold:true};if(n>50)s.freezePanes.freezeRows(5);}
function header(s,row,labels){const r=s.getRange(`B${row}:${col(labels.length+1)}${row}`);r.values=[labels];r.format={fill:'#17324F',font:{color:'#FFFFFF',bold:true},rowHeight:46,wrapText:true,horizontalAlignment:'center'};}
const pp='0.00;[Red](0.00);0.00',factRow={};
let s=sh['PG facts'];setup(s,'P&G published facts',[18,39,19,19,19,18,70],facts.length+6);header(s,5,['Quarter ended','Segment','Volume growth %','Pricing contribution pp','Organic sales growth %','Published','Original report']);
s.getRange(`B6:H${facts.length+5}`).values=facts.map((r,i)=>{factRow[r.segment+'|'+r.period_end]=i+6;return[D(r.period_end),r.segment,r.organic_volume_growth??null,r.price_contribution??null,r.organic_sales_growth??null,D(r.publication_date),sources.find(x=>x.period===r.period_end).url];});s.getRange(`B6:B${facts.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`G6:G${facts.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`D6:F${facts.length+5}`).setNumberFormat(pp);
const mc={organic_volume_growth:'D',price_contribution:'E',organic_sales_growth:'F'};
const ranges={};s=sh['Training pairs'];setup(s,'Training pairs known at each forecast date',[14,15,18,18,20,20,20,20],train.length+6);header(s,5,['Forecast ID','Method','Company quarter','Published','Market YoY %','P&G result','Market squared','Cross product']);
s.getRange(`B6:F${train.length+5}`).values=train.map((r,i)=>{const k=r.prediction_id+'|'+r.method;ranges[k]??={start:i+6,end:i+6};ranges[k].end=i+6;return[r.prediction_id,r.method,D(r.company_quarter),D(r.company_published),r.market_growth];});
s.getRange(`G6:I${train.length+5}`).formulas=train.map((r,i)=>{const n=i+6,pr=pred[r.prediction_id-1];return[`='PG facts'!${mc[pr.metric]}${factRow[pr.segment+'|'+r.company_quarter]}`,`=F${n}^2`,`=F${n}*G${n}`];});s.getRange(`D6:E${train.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`F6:I${train.length+5}`).setNumberFormat(pp);
s=sh['Target months'];setup(s,'Observed months and explicit estimates',[14,18,17,22,22,22,22],tm.length+6);V(s,'B3','Unknown months use the latest three observed monthly YoY rates; estimates remain labelled.');header(s,5,['Forecast ID','Target month','Observed?','Observed level','Prior-year level','Carry-forward YoY %','Level used']);s.getRange(`B6:G${tm.length+5}`).values=tm.map(r=>[r.prediction_id,D(r.month),r.observed?'Yes':'No',r.observed?r.value:null,r.prior_year,r.carry_yoy_pct]);s.getRange(`H6:H${tm.length+5}`).formulas=tm.map((r,i)=>[`=IF(D${i+6}="Yes",E${i+6},F${i+6}*(1+G${i+6}/100))`]);s.getRange(`C6:C${tm.length+5}`).setNumberFormat('mmm-yy');s.getRange(`E6:H${tm.length+5}`).setNumberFormat('#,##0.000');
s=sh['Forecast log'];setup(s,'Release-by-release forecast calculations',[14,39,25,18,18,15,18,18,14,18,18,18,18,14,18,18,18,18,18,18,18,65],pred.length+6);V(s,'B3','Download / calendar alignment runs in Python. Excel recalculates fitted coefficients, forecasts and scores.');header(s,5,['ID','Segment','Measure','Target quarter','Known by','Observed months','Four-quarter mean','Last actual','Bridge n','Bridge slope','Bridge intercept','Market nowcast %','Bridge result','Lag n','Lag slope','Lag intercept','Prior-quarter market %','Lag result','50/50 blend','Market version','Latest P&G publication','Market source']);
const modelParts=(pr,method,n,cSlope,cInt,cX)=>{const r=ranges[pr.prediction_id+'|'+method];if(pr[method+'_n']===null)return['="n.a."','="n.a."','="n.a."'];const x=`'Training pairs'!F${r.start}:F${r.end}`,y=`'Training pairs'!G${r.start}:G${r.end}`,xx=`'Training pairs'!H${r.start}:H${r.end}`,xy=`'Training pairs'!I${r.start}:I${r.end}`;return[`=COUNT(${x})`,`=(SUM(${xy})-SUM(${x})*SUM(${y})/COUNT(${x}))/(SUM(${xx})-SUM(${x})^2/COUNT(${x}))`,`=AVERAGE(${y})-${cSlope}${n}*AVERAGE(${x})`];};
for(let i=0;i<pred.length;i++){const r=pred[i],n=i+6;const known=facts.filter(f=>f.segment===r.segment&&f.period_end<r.target_quarter&&f.publication_date<=r.cutoff).sort((a,b)=>a.period_end.localeCompare(b.period_end));const refs=known.slice(-4).map(f=>`'PG facts'!${mc[r.metric]}${factRow[r.segment+'|'+f.period_end]}`);s.getRange(`B${n}:G${n}`).values=[[r.prediction_id,r.segment,r.metric,D(r.target_quarter),D(r.cutoff),r.months_observed]];F(s,'H'+n,`=AVERAGE(${refs.join(',')})`);F(s,'I'+n,`=${refs.at(-1)}`);s.getRange(`J${n}:L${n}`).formulas=[modelParts(r,'bridge',n,'K','L','M')];const t=i*3+6;F(s,'M'+n,`=(SUM('Target months'!H${t}:H${t+2})/SUM('Target months'!F${t}:F${t+2})-1)*100`);F(s,'N'+n,r.bridge===null?'="n.a."':`=L${n}+K${n}*M${n}`);s.getRange(`O${n}:Q${n}`).formulas=[modelParts(r,'lagged',n,'P','Q','R')];V(s,'R'+n,r.lagged_x??'n.a.');F(s,'S'+n,r.lagged===null?'="n.a."':`=Q${n}+P${n}*R${n}`);F(s,'T'+n,r.blend===null?'="n.a."':`=(H${n}+N${n})/2`);s.getRange(`U${n}:W${n}`).values=[[D(r.market_vintage),D(r.latest_company_publication),r.market_url]];}
s.getRange(`E6:F${pred.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`U6:V${pred.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`H6:T${pred.length+5}`).setNumberFormat(pp);s.getRange(`J6:J${pred.length+5}`).setNumberFormat('0');s.getRange(`O6:O${pred.length+5}`).setNumberFormat('0');
const methodCol={baseline:'H',last_actual:'I',bridge:'N',lagged:'S',blend:'T'};
s=sh['Scored quarters'];setup(s,'Score only after P&G publishes actuals',[14,39,25,18,20,18,18,18,18,20,20,20,16,18],scored.length+6);header(s,5,['Forecast ID','Segment','Measure','Quarter','Stage','Method','Prediction','Actual','Error pp','Squared error','Mean error squared','Last actual error squared','Beats mean?','Absolute error']);s.getRange(`B6:G${scored.length+5}`).values=scored.map(r=>[r.prediction_id,r.segment,r.metric,D(r.target_quarter),r.stage,r.method]);s.getRange(`H6:O${scored.length+5}`).formulas=scored.map((r,i)=>{const n=i+6,pn=r.prediction_id+5;return[`='Forecast log'!${methodCol[r.method]}${pn}`,`='PG facts'!${mc[r.metric]}${factRow[r.segment+'|'+r.target_quarter]}`,`=H${n}-I${n}`,`=J${n}^2`,`=('Forecast log'!H${pn}-I${n})^2`,`=('Forecast log'!I${pn}-I${n})^2`,`=IF(ABS(J${n})<SQRT(L${n}),1,0)`,`=ABS(J${n})`];});s.getRange(`E6:E${scored.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`H6:O${scored.length+5}`).setNumberFormat(pp);
s=sh.Scorecard;setup(s,'Model errors on comparable quarters',[39,25,20,18,14,18,18,18,18,18,16],scores.length+6);header(s,5,['Segment','Measure','Stage','Method','Quarters','RMSE pp','Mean RMSE pp','Last actual RMSE pp','MAE pp','Bias pp','Wins vs mean']);const scoreRows={};const end=scored.length+5;const criteria=n=>`'Scored quarters'!$C$6:$C$${end},B${n},'Scored quarters'!$D$6:$D$${end},C${n},'Scored quarters'!$F$6:$F$${end},D${n},'Scored quarters'!$G$6:$G$${end},E${n}`;
s.getRange(`B6:E${scores.length+5}`).values=scores.map((r,i)=>{scoreRows[[r.segment,r.metric,r.stage,r.method].join('|')]=i+6;return[r.segment,r.metric,r.stage,r.method];});s.getRange(`F6:L${scores.length+5}`).formulas=scores.map((r,i)=>{const n=i+6,c=criteria(n),sum=k=>`SUMIFS('Scored quarters'!$${k}$6:$${k}$${end},${c})`;return[`=COUNTIFS(${c})`,`=SQRT(${sum('K')}/F${n})`,`=SQRT(${sum('L')}/F${n})`,`=SQRT(${sum('M')}/F${n})`,`=${sum('O')}/F${n}`,`=SUMIFS('Scored quarters'!$J$6:$J$${end},${c})/F${n}`,`=${sum('N')}`];});s.getRange(`G6:K${scores.length+5}`).setNumberFormat(pp);
s=sh['Market sources'];setup(s,'Preserved ALFRED historical versions',[23,18,18,20,15,65],manifest.length+6);header(s,5,['Series','Version date','Release event?','Last month available','Observations','Public source']);s.getRange(`B6:G${manifest.length+5}`).values=manifest.map(r=>[r.series,D(r.vintage),r.is_release_event?'Yes':'Checkpoint',D(r.latest_month),r.observations,r.source_url]);s.getRange(`C6:C${manifest.length+5}`).setNumberFormat('dd-mmm-yy');s.getRange(`E6:E${manifest.length+5}`).setNumberFormat('mmm-yy');
s=sh['Quarter example'];setup(s,'Grooming pricing: January-March 2026',[20,19,20,20,20,20],42);V(s,'B3','Updates can worsen a forecast. Actual pricing contribution: 3pp, published 24 April.');header(s,5,['Forecast date','Observed months','Last actual rule','Market model','Actual (later)','Model error pp']);const ex=pred.filter(r=>r.segment==='Grooming'&&r.metric==='price_contribution'&&r.target_quarter==='2026-03-31');ex.forEach((r,i)=>{const n=i+6,pn=r.prediction_id+5;s.getRange(`B${n}:G${n}`).formulas=[[`='Forecast log'!F${pn}`,`='Forecast log'!G${pn}`,`='Forecast log'!I${pn}`,`='Forecast log'!N${pn}`,`='PG facts'!E${factRow['Grooming|2026-03-31']}`,`=E${n}-F${n}`]];});s.getRange('B6:B12').setNumberFormat('dd-mmm-yy');s.getRange('D6:G12').setNumberFormat(pp);s.getRange('E12:G12').format.font={color:'#C62828',bold:true};s.getRange('E12:G12').format.borders={preset:'outside',style:'medium',color:'#C62828'};V(s,'B14','Actuals are shown for evaluation only; they do not feed earlier forecasts.');
V(s,'J5','Date label');for(let n=6;n<=12;n++)F(s,'J'+n,`=TEXT(B${n},"dd-mmm")`);const chart=s.charts.add('line',[s.getRange('J5:J12'),s.getRange('D5:D12'),s.getRange('E5:E12'),s.getRange('F5:F12')]);chart.title='Pricing contribution forecasts and eventual actual (pp)';chart.titleTextStyle.fontSize=14;chart.titleTextStyle.typeface='Arial';chart.setPosition('B17','H34');chart.yAxis={numberFormatCode:'0.0',numberFormatSourceLinked:false};chart.xAxis={axisType:'textAxis',textStyle:{typeface:'Arial',fontSize:12}};chart.legend={position:'bottom',textStyle:{typeface:'Arial',fontSize:12}};['#7C8796','#1765A6','#C62828'].forEach((c,i)=>chart.series.items[i].line={fill:c,style:i===2?'dashed':'solid',width:2});
s=sh.Review;setup(s,'P&G release-aware backtest',[39,24,18,18,18,18],36);V(s,'B3','Eight test quarters: April-June 2024 through January-March 2026. Errors in percentage points.');header(s,5,['Business segment','Measure','Market RMSE','Four-quarter mean','Last actual','Test quarters']);const focus=scores.filter(r=>r.stage==='Pre-earnings'&&r.method==='bridge');focus.forEach((r,i)=>{const n=i+6,t=scoreRows[[r.segment,r.metric,r.stage,r.method].join('|')];s.getRange(`B${n}:G${n}`).formulas=[[`=Scorecard!B${t}`,`=Scorecard!C${t}`,`=Scorecard!G${t}`,`=Scorecard!H${t}`,`=Scorecard!I${t}`,`=Scorecard!F${t}`]];});s.getRange('C6:C14').values=focus.map(r=>[{organic_volume_growth:'Volume growth',price_contribution:'Pricing contribution',organic_sales_growth:'Organic sales growth'}[r.metric]]);s.getRange('D6:F14').setNumberFormat(pp);
s.getRange('D6:D14').conditionalFormats.addCustom('D6<MIN(E6,F6)',{font:{color:'#008000',bold:true}});s.getRange('D6:D14').conditionalFormats.addCustom('D6>=MIN(E6,F6)',{font:{color:'#C62828'}});V(s,'B17','Grooming pricing remains a candidate; Beauty barely beats the last-actual rule.');V(s,'B18','No model is approved for automatic scenario changes from eight test quarters.');header(s,21,['Pricing model','Market-only RMSE','50/50 blend RMSE','Conclusion']);['Beauty','Grooming'].forEach((seg,i)=>{const n=i+22,t=scoreRows[[seg,'price_contribution','Pre-earnings','bridge'].join('|')],b=scoreRows[[seg,'price_contribution','Pre-earnings','blend'].join('|')];V(s,'B'+n,seg);F(s,'C'+n,`=Scorecard!G${t}`);F(s,'D'+n,`=Scorecard!G${b}`);F(s,'E'+n,`=IF(D${n}<C${n},"Blend improved","Blend worsened")`);});s.getRange('C22:D23').setNumberFormat(pp);s.getRange('E22:E23').setNumberFormat('  @');V(s,'B26','50/50 blending is tested, not assumed to fix weak data. No regional weights were invented.');V(s,'B27','Frozen inputs preserve historical availability. A rerun is required to add new releases.');V(s,'B28','This is retrospective model development, not an untouched prospective test.');
for(const name of ['Training pairs','Scored quarters','Forecast log','PG facts','Market sources'])sh[name].getRange(`C6:C${name==='Training pairs'?train.length+5:name==='Scored quarters'?scored.length+5:name==='Forecast log'?pred.length+5:name==='PG facts'?facts.length+5:manifest.length+5}`).format.horizontalAlignment='left';
w.recalculate();
for(let i=0;i<pred.length;i++){for(const [key,c] of Object.entries(methodCol)){const expected=pred[i][key],got=sh['Forecast log'].getRange(c+(i+6)).values[0][0];if(expected!==null&&(typeof got!=='number'||Math.abs(got-expected)>1e-7))throw Error(`${key} ${i}: ${got} != ${expected}`);}}
for(let i=0;i<scores.length;i++){const got=sh.Scorecard.getRange('G'+(i+6)).values[0][0];if(typeof got!=='number'||Math.abs(got-scores[i].rmse)>1e-7)throw Error(`Score mismatch ${i}`);}
const input=sh['Target months'].getRange('E'+((447-1)*3+6)),before=sh['Quarter example'].getRange('E12').values[0][0],old=input.values[0][0];input.values=[[old+1]];w.recalculate();if(sh['Quarter example'].getRange('E12').values[0][0]===before)throw Error('Input did not flow to forecast');input.values=[[old]];w.recalculate();
const actualCell=sh['PG facts'].getRange('E'+factRow['Grooming|2026-03-31']),actualOld=actualCell.values[0][0],frozen=sh['Quarter example'].getRange('E12').values[0][0];actualCell.values=[[99]];w.recalculate();if(sh['Quarter example'].getRange('E12').values[0][0]!==frozen)throw Error('Target actual leaked into forecast');actualCell.values=[[actualOld]];w.recalculate();
console.log((await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!',options:{useRegex:true,maxResults:20}})).ndjson);
await fs.mkdir(out,{recursive:true});for(const n of names){const end=n==='Review'?'G28':n==='Quarter example'?'G14':n==='Scorecard'?'L13':n==='Forecast log'?'N12':n==='Training pairs'?'I13':n==='Target months'?'H13':n==='Scored quarters'?'K13':n==='PG facts'?'G13':'F13';const im=await w.render({sheetName:n,range:'B2:'+end,scale:1.1});await fs.writeFile(out+'/'+n.replaceAll(' ','_')+'.png',new Uint8Array(await im.arrayBuffer()));}
const cim=await w.render({sheetName:'Quarter example',range:'B17:H34',scale:1.2});await fs.writeFile(out+'/chart.png',new Uint8Array(await cim.arrayBuffer()));
await(await SpreadsheetFile.exportXlsx(w)).save(out+'/PG_5_Release_Aware_Backtest.xlsx');await fs.writeFile(out+'/validation.json',JSON.stringify({all_forecasts_match_python:true,all_scores_match_python:true,input_recalculates_example:true,input_restored:true,target_actual_mutation_does_not_change_earlier_forecast:true},null,2));console.log('Workbook and nine sheet previews saved');
