import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=decodeURIComponent(new URL('../',import.meta.url).pathname),p=root+'data/april24_forecast/',out=root+'outputs/april24_forecast';
const read=async n=>JSON.parse(await fs.readFile(p+n+'.json','utf8'));
const [rows,actual,training,market,raw,selection,diagnosis]=await Promise.all(['variance','actuals','training_pairs','market_forecast','market_inputs','model_selection','error_diagnosis'].map(read));
const w=Workbook.create(),names=['Forecast vs Actual','Forecast build','Market build','Sources'],sh=Object.fromEntries(names.map(n=>[n,w.worksheets.add(n)]));
const C=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;},V=(s,c,v)=>s.getRange(c).values=[[v]],F=(s,c,v)=>s.getRange(c).formulas=[[v]],D=s=>new Date(s+'T00:00:00Z');
const pp='0.00;[Red](0.00);0.00',money='"$"#,##0.00;[Red]("$"#,##0.00);"$"0.00';
const label=r=>r.segment.replace('Baby, Feminine & Family Care','Baby / Feminine / Family')+' / '+({organic_volume_growth:'volume',organic_sales_growth:'organic sales',price_contribution:'pricing'}[r.metric]);
function setup(s,title,widths,n){s.showGridLines=false;s.getRange(`A1:${C(widths.length+1)}${n}`).format={font:{name:'Arial',size:12,color:'#17324F'},rowHeight:28,verticalAlignment:'center'};s.getRange(`A1:A${n}`).format.columnWidth=3;widths.forEach((v,i)=>s.getRange(`${C(i+2)}1:${C(i+2)}${n}`).format.columnWidth=v);V(s,'B2',title);s.getRange('B2').format.font={size:18,bold:true};if(n>80)s.freezePanes.freezeRows(5);}
function head(s,n,a){s.getRange(`B${n}:${C(a.length+1)}${n}`).values=[a];s.getRange(`B${n}:${C(a.length+1)}${n}`).format={fill:'#17324F',font:{color:'#FFFFFF',bold:true},wrapText:true,rowHeight:46,horizontalAlignment:'center'};}
function red(s,r){s.getRange(r).format.font={color:'#C62828',bold:true};s.getRange(r).format.borders={preset:'outside',style:'medium',color:'#C62828'};}
function signs(s,r){s.getRange(r).conditionalFormats.add('cellIs',{operator:'lessThan',formula:0,format:{font:{color:'#C62828'}}});s.getRange(r).conditionalFormats.add('cellIs',{operator:'greaterThan',formula:0,format:{font:{color:'#16724B'}}});}
let s=sh.Sources;setup(s,'Published values | Forecast inputs and later actuals',[48,24,24,24,25],raw.length+40);head(s,5,['Financial input','Value','Period / published']);
s.getRange('B6:D12').values=[['Prior-year sales ($m)',84284,'FY ended Jun 2025'],['Nine-month sales ($m)',65829,'Jul 2025–Mar 2026'],['Prior-year quarter sales ($m)',20889,'Apr–Jun 2025'],['Annual guidance midpoint',.03,'Available 24-Apr-2026'],['Actual quarter sales ($m)',actual.net_sales_m,'Released 29-Jul-2026'],['Actual annual sales ($m)',actual.full_year_sales_m,'Released 29-Jul-2026'],['Forecast cutoff',D('2026-04-24'),'End of day']];s.getRange('C6:C8').setNumberFormat(money);s.getRange('C9').setNumberFormat('0.0%');s.getRange('C10:C11').setNumberFormat(money);s.getRange('C12').setNumberFormat('dd-mmm-yyyy');
V(s,'B14','Prior figures: PG_2_Quarter_Sales_Target.xlsx / analysis question 2.');V(s,'B15','https://www.pginvestor.com/news/news-details/2026/PG-Announces-Fiscal-Year-2026-Third-Quarter-Results/default.aspx');V(s,'B16',actual.source_url);
head(s,18,['Later actual: Apr–Jun 2026','Volume growth %','Pricing pp','Organic sales %']);s.getRange('B19:E23').values=actual.segments.map(r=>[r.segment,r.organic_volume_growth,r.price_contribution,r.organic_sales_growth]);s.getRange('C19:E23').setNumberFormat(pp);const ar=Object.fromEntries(actual.segments.map((r,i)=>[r.segment,i+19]));
head(s,26,['Original market series','Observation month','Level (24-Apr vintage)']);s.getRange(`B27:D${raw.length+26}`).values=raw.map(r=>[r.series,D(r.month),r.level]);s.getRange(`C27:C${raw.length+26}`).setNumberFormat('mmm-yy');s.getRange(`D27:D${raw.length+26}`).setNumberFormat('0.000');const rawref=Object.fromEntries(raw.map((r,i)=>[r.series+'|'+r.month,i+27]));s.getRange(`C6:C12`).format.font={color:'#0000FF'};
s=sh['Market build'];setup(s,'Estimate April–June with data available on 24 April',[25,20,21,22,22,22],43);head(s,5,['Market series','Method','Latest month','Quarter growth %']);const codes=[...new Set(market.map(r=>r.series))],growthrow={};
codes.forEach((code,i)=>{const rs=market.filter(r=>r.series===code),n=14+i*7;growthrow[code]=n+4;V(s,'B'+n,code);head(s,n+1,['Target month','Prior-year level','Latest actual level','Forecast level','Growth vs prior year']);rs.forEach((r,j)=>{const k=n+j+2;V(s,'B'+k,D(r.month));F(s,'C'+k,`=Sources!D${rawref[code+'|'+r.month.replace('2026','2025')]}`);F(s,'D'+k,`=Sources!D${rawref[code+'|'+r.latest_month]}`);F(s,'E'+k,r.method==='Flat level'?`=D${k}`:`=C${k}*(1+$H$${i+6}/100)`);F(s,'F'+k,`=100*(E${k}/C${k}-1)`);});V(s,'B'+(n+5),'Quarter YoY %');F(s,'E'+(n+5),`=100*(SUM(E${n+2}:E${n+4})/SUM(C${n+2}:C${n+4})-1)`);growthrow[code]=n+5;s.getRange(`B${n+2}:B${n+4}`).setNumberFormat('mmm-yy');s.getRange(`C${n+2}:F${n+5}`).setNumberFormat(pp);s.getRange(`B${i+6}:D${i+6}`).values=[[code,rs[0].method,D(rs[0].latest_month)]];F(s,'E'+(i+6),`=E${n+5}`);
// Carry-growth input is calculated from the latest three available YoY comparisons.
const obs=raw.filter(r=>r.series===code).sort((a,b)=>a.month.localeCompare(b.month));const last=obs.slice(-3);const refs=last.map(r=>{const prior=String(+r.month.slice(0,4)-1)+r.month.slice(4);return`(Sources!D${rawref[code+'|'+r.month]}/Sources!D${rawref[code+'|'+prior]}-1)*100`;});F(s,'H'+(i+6),`=AVERAGE(${refs.join(',')})`);});V(s,'H5','Recent YoY average %');s.getRange('D6:D9').setNumberFormat('mmm-yy');s.getRange('E6:E9').setNumberFormat(pp);s.getRange('H6:H9').setNumberFormat(pp);s.getRange('H5:H9').format.columnWidth=24;V(s,'B11','No April, May or June market actual is used. Consumption was available only through February.');
s=sh['Forecast build'];setup(s,'Six separate forecasts | Model choice fixed before scoring',[47,25,18,12,...Array(12).fill(18)],training.length+30);head(s,5,['P&G measure','Selected method','Market series','n','Sum x','Sum y','Sum xx','Sum xy','Slope','Intercept','Market growth %','Model forecast','Last actual','4-qtr mean','Selected forecast','Actual (later)']);
head(s,25,['Historical training pair','Quarter','Published','Market growth','PG result']);s.getRange(`B26:F${training.length+25}`).values=training.map(r=>[label(r),D(r.company_quarter),D(r.published),r.market_growth,r.company_growth]);s.getRange(`C26:D${training.length+25}`).setNumberFormat('dd-mmm-yy');s.getRange(`E26:F${training.length+25}`).setNumberFormat(pp);
rows.forEach((r,i)=>{const n=i+6,ix=training.flatMap((z,k)=>z.segment===r.segment&&z.metric===r.metric?[k+26]:[]),first=ix[0],last=ix.at(-1),x=`E${first}:E${last}`,y=`F${first}:F${last}`;s.getRange(`B${n}:D${n}`).values=[[label(r),r.selected_model,r.series]];F(s,'E'+n,`=COUNT(${x})`);F(s,'F'+n,`=SUM(${x})`);F(s,'G'+n,`=SUM(${y})`);F(s,'H'+n,`=SUMPRODUCT(${x},${x})`);F(s,'I'+n,`=SUMPRODUCT(${x},${y})`);F(s,'J'+n,`=(I${n}-F${n}*G${n}/E${n})/(H${n}-F${n}^2/E${n})`);F(s,'K'+n,`=G${n}/E${n}-J${n}*F${n}/E${n}`);F(s,'L'+n,`='Market build'!E${growthrow[r.series]}`);F(s,'M'+n,`=K${n}+J${n}*L${n}`);V(s,'N'+n,r.last_actual);V(s,'O'+n,r.four_mean);F(s,'P'+n,`=IF(C${n}="Market model",M${n},IF(C${n}="Last actual",N${n},O${n}))`);F(s,'Q'+n,`=Sources!${{organic_volume_growth:'C',price_contribution:'D',organic_sales_growth:'E'}[r.metric]}${ar[r.segment]}`);});s.getRange('F6:Q11').setNumberFormat(pp);s.getRange('B6:D11').format.wrapText=true;s.getRange('B6:Q11').format.rowHeight=44;
V(s,'B13','Methods were chosen using the preceding zero-target-month backtest; timing is not identical to 24 April.');V(s,'B14','These forecasts are separate tests. They are not additive or a reconciled company revenue forecast.');
head(s,16,['Model check: error pp','Forecast − actual','Relationship error','Market-input error']);rows.forEach((r,i)=>{const n=i+17;V(s,'B'+n,label(r));F(s,'C'+n,`=M${i+6}-Q${i+6}`);V(s,'H'+n,diagnosis[i].later_market_growth);F(s,'I'+n,`=K${i+6}+J${i+6}*H${n}`);F(s,'D'+n,`=I${n}-Q${i+6}`);F(s,'E'+n,`=M${i+6}-I${n}`);});s.getRange('C17:E22').setNumberFormat(pp);V(s,'H15','Later market growth %');V(s,'I15','Later-input prediction');V(s,'G23','1 August market version: diagnostic only, not a forecast input.');s.getRange('H17:I22').setNumberFormat(pp);
s=sh['Forecast vs Actual'];setup(s,'P&G | 24 April forecast vs April–June actual',[46,22,22,22,22,23],49);V(s,'B3','Forecast cutoff: 24-Apr-2026 · Actual report: 29-Jul-2026 · Variance = actual − forecast');
head(s,5,['Sales reference ($m)','Reference','Actual','Variance $m','Variance %']);V(s,'B6','Guidance midpoint implied quarter');F(s,'C6','=Sources!C6*(1+Sources!C9)-Sources!C7');F(s,'D6','=Sources!C10');F(s,'E6','=D6-C6');F(s,'F6','=E6/C6');s.getRange('C6:E6').setNumberFormat(money);s.getRange('F6').setNumberFormat('0.00%');signs(s,'E6:F6');V(s,'B8','Reference only: this is not our independent sales forecast or P&G’s internal budget.');
head(s,10,['Independent P&G tests','Forecast','Actual','Variance pp','Method used']);rows.forEach((r,i)=>{const n=i+11;V(s,'B'+n,label(r));F(s,'C'+n,`='Forecast build'!P${i+6}`);F(s,'D'+n,`='Forecast build'!Q${i+6}`);F(s,'E'+n,`=D${n}-C${n}`);V(s,'F'+n,r.selected_model);});s.getRange('B11:F16').format.rowHeight=42;s.getRange('B11:B16').format.wrapText=true;s.getRange('F11:F16').format.wrapText=true;s.getRange('C11:D16').setNumberFormat('0.00"%";[Red](0.00"%");0.00"%"');s.getRange('C14:D14').setNumberFormat('0.00"pp";[Red](0.00"pp");0.00"pp"');s.getRange('C16:D16').setNumberFormat('0.00"pp";[Red](0.00"pp");0.00"pp"');s.getRange('F11:F16').format.horizontalAlignment='center';s.getRange('E11:E16').setNumberFormat(pp);signs(s,'E11:E16');red(s,'C14:E14');V(s,'B18','Pricing = contribution to growth. A positive variance means above forecast, not necessarily better profit.');
head(s,20,['Accuracy: six equal-weight tests','Selected methods','Last actual','4-qtr mean']);V(s,'B21','Average absolute error pp');F(s,'C21',`=AVERAGE(${rows.map((r,i)=>`ABS(E${i+11})`).join(',')})`);F(s,'D21',`=AVERAGE(${rows.map((r,i)=>`ABS('Forecast build'!N${i+6}-D${i+11})`).join(',')})`);F(s,'E21',`=AVERAGE(${rows.map((r,i)=>`ABS('Forecast build'!O${i+6}-D${i+11})`).join(',')})`);s.getRange('C21:E21').setNumberFormat(pp);red(s,'C21:E21');V(s,'B23','The four-quarter average wins this quarter. Six measures are not six independent quarters.');
head(s,26,['What needs attention','Finding']);s.getRange('B27:C29').values=[['Beauty pricing','4.31pp forecast vs 1pp actual'],['Market estimate or relationship?','Later market data still implies 5.41pp'],['Interpretation','The relationship needs review']];s.getRange('C27:C29').format.columnWidth=22;s.getRange('B27:C29').format.wrapText=true;s.getRange('B27:C29').format.rowHeight=42;
V(s,'B31','Sales calculation');V(s,'B32','Prior-year annual sales ($m)');F(s,'C32','=Sources!C6');V(s,'B33','Annual growth midpoint');F(s,'C33','=Sources!C9');V(s,'B34','Required annual sales ($m)');F(s,'C34','=C32*(1+C33)');V(s,'B35','Less: July–March actual sales ($m)');F(s,'C35','=Sources!C7');V(s,'B36','Required April–June sales ($m)');F(s,'C36','=C34-C35');s.getRange('C32:C36').setNumberFormat(money);s.getRange('C33').setNumberFormat('0.0%');V(s,'B38','Reconciliation: prior nine months + actual quarter − annual actual');F(s,'C39','=Sources!C7+Sources!C10-Sources!C11');s.getRange('C39').setNumberFormat('0.00');
w.recalculate();const close=(a,b,l)=>{if(typeof a!=='number'||Math.abs(a-b)>1e-7)throw Error(l+': '+a+' vs '+b);};rows.forEach((r,i)=>{close(sh['Forecast build'].getRange('P'+(i+6)).values[0][0],r.forecast,'frozen forecast');close(s.getRange('E'+(i+11)).values[0][0],r.variance_pp,'variance');});close(s.getRange('E6').values[0][0],219.48,'sales difference');close(s.getRange('C39').values[0][0],0,'sales reconciliation');const old=sh.Sources.getRange('C10').values[0][0];V(sh.Sources,'C10',old+1);w.recalculate();close(s.getRange('E6').values[0][0],220.48,'input recalc');V(sh.Sources,'C10',old);w.recalculate();
await fs.mkdir(out,{recursive:true});await fs.writeFile(out+'/formula_check.ndjson',(await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!',options:{useRegex:true,maxResults:20}})).ndjson);await(await SpreadsheetFile.exportXlsx(w)).save(out+'/PG_8_April24_Forecast_vs_Actual.xlsx');
for(const [name,range] of [['Forecast vs Actual','B2:F23'],['Forecast build','B16:E22'],['Market build','B14:F19'],['Sources','B18:E23']])await fs.writeFile(out+'/'+name.replaceAll(' ','_')+'.png',new Uint8Array(await(await w.render({sheetName:name,range,scale:1.4})).arrayBuffer()));
await fs.writeFile(out+'/validation.json',JSON.stringify({six_forecasts_match_frozen_inputs:true,six_variances_checked:true,sales_variance_checked:true,sales_reconciliation_zero:true,recalculation_checked_and_restored:true},null,2));console.log('PG_8 workbook saved');
