import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=decodeURIComponent(new URL('../',import.meta.url).pathname),p=root+'data/history_rebuild/',out=root+'outputs/history_review';
await fs.mkdir(out,{recursive:true});
const read=async n=>JSON.parse(await fs.readFile(p+n+'.json','utf8'));
const history=await read('pg_quarterly'),monthly=await read('market_monthly'),quarterly=await read('market_quarterly'),matched=await read('matched_quarters'),tests=await read('sensitivity_tests'),products=await read('product_prices_research_only'),observations=await read('pg_observations'),events=await read('release_updates');
const w=Workbook.create();
const names=['Review','Product match','Model tests','Matched quarters','Quarterly market','PG history','Monthly market','Product prices','Source evidence'];
const sheets=Object.fromEntries(names.map(n=>[n,w.worksheets.add(n)]));
const V=(s,c,v)=>s.getRange(c).values=[[v]],F=(s,c,v)=>s.getRange(c).formulas=[[v]];
const col=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;};
function setup(s,title,widths,rows){s.showGridLines=false;const range=s.getRange(`A1:${col(widths.length+1)}${rows}`);range.format.font={name:'Arial',size:12,color:'#17324F'};range.format.rowHeight=25;range.format.verticalAlignment='center';s.getRange(`A1:A${rows}`).format.columnWidth=3;widths.forEach((a,i)=>s.getRange(`${col(i+2)}1:${col(i+2)}${rows}`).format.columnWidth=a);V(s,'B2',title);s.getRange('B2').format.font={size:18,bold:true};if(rows>50)s.freezePanes.freezeRows(5);}
function header(s,row,labels){s.getRange(`B${row}:${col(labels.length+1)}${row}`).values=[labels];s.getRange(`B${row}:${col(labels.length+1)}${row}`).format={fill:'#17324F',font:{color:'#FFFFFF',bold:true},rowHeight:44,wrapText:true,horizontalAlignment:'center',verticalAlignment:'center'};}
const pctpp='0.00"%";(0.00)"%";0.00"%"',money='"$"#,##0;("$"#,##0);"$"0';
let s=sheets['PG history'];setup(s,'P&G | Quarterly facts',[19,39,20,18,18,18,18,18,18,18],126);V(s,'B3','January 2022–March 2026. Sales in USD millions; growth and contributions in %.');header(s,5,['Quarter ended','Business segment','Net sales','Sales growth','Organic growth','Organic volume','Pricing','Mix','FX','Published']);
const histLookup={};history.forEach((r,i)=>{const n=i+6;s.getRange(`B${n}:K${n}`).values=[[r.period_end,r.segment,r.net_sales,r.reported_sales_growth,r.organic_sales_growth,r.organic_volume_growth,r.price_contribution,r.mix_contribution,r.fx_contribution,r.publication_date]];histLookup[r.period_end+'|'+r.segment]=n;});s.getRange('D6:D124').setNumberFormat(money);s.getRange('E6:J124').setNumberFormat(pctpp);s.getRange('D6:J124').format.font.color='#008000';
const mnLookup={};s=sheets['Monthly market'];setup(s,'Monthly market | Date-frozen inputs',[22,19,19,20,68,65],monthly.length+7);header(s,5,['Series','Known by','Month','Value','Units','Source']);monthly.forEach((r,i)=>{const n=i+6;s.getRange(`B${n}:G${n}`).values=[[r.series,r.vintage,r.month,r.value,r.unit,r.source_url]];mnLookup[r.series+'|'+r.vintage+'|'+r.month]=n;});s.getRange(`E6:E${monthly.length+5}`).setNumberFormat('#,##0.000');
s=sheets['Quarterly market'];setup(s,'Monthly to quarterly | Match periods first',[22,19,19,21,21,20,15],quarterly.length+7);header(s,5,['Series','Known by','Quarter ended','Quarter level','Prior-year level','Year-on-year %','Months']);const qLookup={};
for(let i=0;i<quarterly.length;i++){const r=quarterly[i],n=i+6;const months=(date)=>{const m=Number(date.slice(5,7));return[m-2,m-1,m].map(v=>date.slice(0,4)+'-'+String(v).padStart(2,'0')+'-01');};const refs=d=>months(d).map(m=>`'Monthly market'!E${mnLookup[r.series+'|'+r.vintage+'|'+m]}`).join(',');s.getRange(`B${n}:D${n}`).values=[[r.series,r.vintage,r.period_end]];F(s,'E'+n,`=${r.aggregation==='sum'?'SUM':'AVERAGE'}(${refs(r.period_end)})`);F(s,'F'+n,`=${r.aggregation==='sum'?'SUM':'AVERAGE'}(${refs(String(Number(r.period_end.slice(0,4))-1)+r.period_end.slice(4))})`);F(s,'G'+n,`=(E${n}/F${n}-1)*100`);V(s,'H'+n,3);qLookup[r.series+'|'+r.vintage+'|'+r.period_end]=n;}
s.getRange(`E6:F${quarterly.length+5}`).setNumberFormat('#,##0.00');s.getRange(`G6:G${quarterly.length+5}`).setNumberFormat(pctpp);
const metricCol={organic_volume_growth:'G',price_contribution:'H',organic_sales_growth:'F'};
const key=r=>[r.segment,r.company_metric,r.market_series,r.vintage].join('|');const ranges={};
s=sheets['Matched quarters'];setup(s,'Quarterly pairs | Company and market',[39,24,21,19,19,20,20,18,18,18,18,18,18,18,18,18],matched.length+7);header(s,5,['Segment','Company measure','Market series','Known by','Quarter ended','Market YoY %','P&G %','Market squared','P&G squared','Cross product','Fitted P&G %','Residual pp','Rolling fit %','Trailing-four %','Fit error squared','Baseline error squared']);
matched.forEach((r,i)=>{const n=i+6,k=key(r);ranges[k]??={start:n,end:n};ranges[k].end=n;s.getRange(`B${n}:F${n}`).values=[[r.segment,r.company_metric,r.market_series,r.vintage,r.period_end]];F(s,'G'+n,`='Quarterly market'!G${qLookup[r.market_series+'|'+r.vintage+'|'+r.period_end]}`);F(s,'H'+n,`='PG history'!${metricCol[r.company_metric]}${histLookup[r.period_end+'|'+r.segment]}`);F(s,'I'+n,`=G${n}*G${n}`);F(s,'J'+n,`=H${n}*H${n}`);F(s,'K'+n,`=G${n}*H${n}`);});
const beta=(start,end)=>`(SUM(K${start}:K${end})-SUM(G${start}:G${end})*SUM(H${start}:H${end})/COUNT(G${start}:G${end}))/(SUM(I${start}:I${end})-SUM(G${start}:G${end})^2/COUNT(G${start}:G${end}))`;
s=sheets['Model tests'];setup(s,'Sensitivity tests | Association is not causation',[39,25,23,19,12,16,16,17,18,18,24],tests.length+9);V(s,'B3','US proxies vs global segments. No coefficient is approved for a sales adjustment.');header(s,5,['Segment','P&G measure','Market series','Known by','Quarters','Slope (pp/pp)','Intercept','R-squared','Fit RMSE (pp)','Baseline RMSE','Forecast use']);
tests.forEach((r,i)=>{const n=i+6,{start:a,end:b}=ranges[key(r)],m=sheets['Matched quarters'];s.getRange(`B${n}:E${n}`).values=[[r.segment,r.company_metric,r.market_series,r.vintage]];F(s,'F'+n,`=COUNT('Matched quarters'!G${a}:G${b})`);const sum=c=>`SUM('Matched quarters'!${c}${a}:${c}${b})`;const cov=`(${sum('K')}-${sum('G')}*${sum('H')}/F${n})`,vx=`(${sum('I')}-${sum('G')}^2/F${n})`,vy=`(${sum('J')}-${sum('H')}^2/F${n})`;F(s,'G'+n,`=${cov}/${vx}`);F(s,'H'+n,`=${sum('H')}/F${n}-G${n}*${sum('G')}/F${n}`);F(s,'I'+n,`=${cov}^2/(${vx}*${vy})`);F(s,'J'+n,`=SQRT(AVERAGE('Matched quarters'!P${a+8}:P${b}))`);F(s,'K'+n,`=SQRT(AVERAGE('Matched quarters'!Q${a+8}:Q${b}))`);V(s,'L'+n,'Not approved');for(let t=a;t<=b;t++){F(m,'L'+t,`='Model tests'!H${n}+'Model tests'!G${n}*G${t}`);F(m,'M'+t,`=H${t}-L${t}`);if(t>=a+8){F(m,'N'+t,`=AVERAGE(H${a}:H${t-1})+(${beta(a,t-1)})*(G${t}-AVERAGE(G${a}:G${t-1}))`);F(m,'O'+t,`=AVERAGE(H${t-4}:H${t-1})`);F(m,'P'+t,`=(H${t}-N${t})^2`);F(m,'Q'+t,`=(H${t}-O${t})^2`);}}});s.getRange('G6:K23').setNumberFormat('0.000');s.getRange('I6:I23').setNumberFormat('0.0%');s.getRange('J6:K23').conditionalFormats.add('dataBar',{color:'#8FAED0'});
s=sheets['Product prices'];setup(s,'Product prices | Research only',[24,65,19,20,60],products.length+8);V(s,'B3','Current-vintage BLS history. Not used in April/May forecast calculations.');header(s,5,['Series','Product group','Month','Price index','Vintage status']);products.forEach((r,i)=>s.getRange(`B${i+6}:F${i+6}`).values=[[r.series,r.category,r.month,r.value,r.vintage]]);s.getRange(`E6:E${products.length+5}`).setNumberFormat('0.000');
s=sheets['Source evidence'];setup(s,'Source evidence | Trace each P&G input',[19,39,27,20,19,45,72,95],observations.length+7);header(s,5,['Quarter','Segment','Measure','Value','Published','Table / row','Original report','Original row']);observations.forEach((r,i)=>s.getRange(`B${i+6}:I${i+6}`).values=[[r.period_end,r.segment,r.metric,r.value,r.publication_date,r.locator,r.source_url,r.excerpt]]);
const mapping=[['Hair Care','Beauty','Hair/dental/shaving CPI','US prices; combined basket'],['Personal Care','Beauty','Personal care products CPI','US prices; broad basket'],['Skin Care','Beauty','Cosmetics/bath CPI','US prices; broader products'],['Grooming','Grooming','Hair/dental/shaving CPI','US prices; combined basket'],['Oral Care','Health Care','Hair/dental/shaving CPI','US prices; combined basket'],['Personal Health Care','Health Care','Health/personal store sales','Channel sales; includes other products'],['Fabric Care','Fabric & Home Care','Household cleaning CPI','US prices; not units sold'],['Home Care','Fabric & Home Care','Household cleaning CPI','US prices; not units sold'],['Baby Care','Baby, Feminine & Family Care','No matched diaper quantity series','Do not substitute baby food'],['Feminine Care','Baby, Feminine & Family Care','No matched quantity series','Do not infer from baby care'],['Family Care','Baby, Feminine & Family Care','Household paper CPI','US prices; not units sold']];
s=sheets['Product match'];setup(s,'Product matching | Use the right level',[25,39,43,46],23);V(s,'B3','Research 11 categories. Financial history covers five global reportable segments.');header(s,5,['Product line','P&G reporting segment','Market evidence collected / gap','What it can tell us']);s.getRange('B6:E16').values=mapping;s.getRange('B6:E16').format.wrapText=true;s.getRange('B6:E16').format.rowHeight=44;V(s,'B19','Peers are optional: use them to test market vs company-specific explanations.');V(s,'B20','No peer coefficient is used here. A future peer model must use the same history window.');V(s,'B21','Match product, geography, units, accounting scope and publication dates first.');
s=sheets.Review;setup(s,'P&G | Test before changing the forecast',[39,17,18,19,22,22,20,20],45);V(s,'B3','17 quarters. Five business segments. Two information cutoffs.');V(s,'B4','Decision: remove the unsupported sales cut; do not replace it with a weak coefficient.');header(s,6,['Global P&G volume vs US nondurables','Quarters','Slope (pp/pp)','R-squared','Forecast use']);
for(let i=0;i<5;i++){const n=7+i,t=15+i;F(s,'B'+n,`='Model tests'!B${t}`);F(s,'C'+n,`='Model tests'!F${t}`);F(s,'D'+n,`='Model tests'!G${t}`);F(s,'E'+n,`='Model tests'!I${t}`);F(s,'F'+n,`='Model tests'!L${t}`);}s.getRange('D7:D11').setNumberFormat('0.000');s.getRange('E7:E11').setNumberFormat('0.0%');s.getRange('B11:F11').format.borders={preset:'outside',style:'medium',color:'#C62828'};s.getRange('D11:E11').format.font={bold:true,color:'#C62828'};
V(s,'B13','Baby, Feminine & Family Care is a combined segment—not Baby Care alone.');V(s,'B14','Slope measures historical association. It is not a causal sales elasticity.');V(s,'B15','Market tests use one historical vintage per cutoff; they are not real-time backtests.');
header(s,17,['New information by 15 May','Period added','Change vs prior month','Action']);events.forEach((r,i)=>{s.getRange(`B${18+i}:E${18+i}`).values=[[{CUUR0000SEGB:'US personal care prices (NSA)',PCENDC96:'US real nondurable spending (SA)',RSHPCS:'US health/personal store sales (SA)'}[r.series],r.new_observation_months,r.monthly_change_pct,'Review; no automatic sales cut']];});s.getRange('D18:D20').setNumberFormat(pctpp);s.getRange('E18:E20').format.wrapText=true;s.getRange('B18:E20').format.rowHeight=40;
V(s,'B22','Company actuals stop at March 2026; April–June results are excluded.');V(s,'B23','April CPI = prices. Retail sales = money spent. Neither equals P&G unit volume.');
V(s,'B24','R-squared describes past co-movement, not forecast accuracy.');
const babyRange=ranges['Baby, Feminine & Family Care|organic_volume_growth|PCENDC96|2026-05-15'];
header(s,26,['Quarter','US nondurable growth','P&G segment volume']);for(let i=0;i<17;i++){const rr=27+i,mr=babyRange.start+i;F(s,'B'+rr,`='Matched quarters'!F${mr}`);F(s,'C'+rr,`='Matched quarters'!G${mr}`);F(s,'D'+rr,`='Matched quarters'!H${mr}`);}s.getRange('C27:D43').setNumberFormat(pctpp);
const chart=s.charts.add('scatter',[s.getRange('C26:C43'),s.getRange('D26:D43')]);chart.setPosition('F26','J44');chart.title='US demand vs combined-segment volume';chart.titleTextStyle.fontSize=14;chart.titleTextStyle.typeface='Arial';chart.legend={visible:false};chart.xAxis={numberFormatCode:'0.0"%"',numberFormatSourceLinked:false};chart.yAxis={numberFormatCode:'0.0"%"',numberFormatSourceLinked:false};chart.xAxis.title.text='US nondurable consumption growth';chart.yAxis.title.text='P&G segment organic volume growth';chart.series.items[0].fill='#1765A6';
sheets['Matched quarters'].getRange(`G6:Q${matched.length+5}`).setNumberFormat('0.000');
for(const address of ['D122','G122']){sheets['PG history'].getRange(address).format.font.color='#C62828';sheets['PG history'].getRange(address).format.borders={preset:'outside',style:'medium',color:'#C62828'};}
w.recalculate();
tests.forEach((r,i)=>{const n=i+6;for(const [c,key] of [['G','beta'],['H','intercept'],['I','r_squared'],['J','diagnostic_rmse'],['K','trailing4_rmse']]){const got=sheets['Model tests'].getRange(c+n).values[0][0];if(typeof got!=='number'||Math.abs(got-r[key])>1e-7)throw Error(`${key} mismatch ${n}: ${got} vs ${r[key]}`);}});
const before=sheets.Review.getRange('D11').values[0][0],row=histLookup['2026-03-31|Baby, Feminine & Family Care'],cell=sheets['PG history'].getRange('G'+row),original=cell.values[0][0];cell.values=[[original+1]];w.recalculate();if(sheets.Review.getRange('D11').values[0][0]===before)throw Error('Sensitivity did not recalculate');cell.values=[[original]];w.recalculate();
console.log((await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#SPILL!',options:{useRegex:true,maxResults:20}})).ndjson);
for(const name of names){const range=name==='Review'?'B2:F23':name==='Product match'?'B2:E21':name==='Model tests'?'B14:L23':name==='PG history'?'B110:K124':name==='Source evidence'?'B2:G12':name==='Matched quarters'?'B2:H13':name==='Product prices'?'B2:F13':name==='Monthly market'?'B2:F13':'B2:H13';const im=await w.render({sheetName:name,range,scale:1.3});await fs.writeFile(out+'/'+name.toLowerCase().replaceAll(' ','_')+'_preview.png',new Uint8Array(await im.arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(w)).save(out+'/PG_4_Historical_Market_Analysis.xlsx');
const chartImage=await w.render({sheetName:'Review',range:'F26:J44',scale:1.5});await fs.writeFile(out+'/scatter_preview.png',new Uint8Array(await chartImage.arrayBuffer()));
await fs.writeFile(out+'/validation.json',JSON.stringify({formula_results_match_independent_python:true,input_change_recalculates_summary:true,quarters:17,market_vintages:2,approved_forecast_coefficients:0},null,2));console.log('Workbook exported and formula checks passed.');
