import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=decodeURIComponent(new URL('../',import.meta.url).pathname),read=async n=>JSON.parse(await fs.readFile(root+'data/variance_causes/'+n+'.json','utf8'));
const [fin,prob,count,cal,common,cost,research,market,sens]=await Promise.all(['financials','probabilities','counts','calibration','common_errors','cost_drivers','research','market_comparison','sensitivity'].map(read));
const config=await read('simulation_config');
const w=Workbook.create(),sh=Object.fromEntries(['Review','Probabilities','Calculations','Sources'].map(n=>[n,w.worksheets.add(n)]));
const V=(s,c,v)=>s.getRange(c).values=[[v]],F=(s,c,f)=>s.getRange(c).formulas=[[f]],C=i=>String.fromCharCode(64+i),pp='0.00;[Red](0.00);"—"',money='"$"#,##0;[Red]("$"#,##0);"—"';
function setup(s,title,widths,rows){s.showGridLines=false;s.getRange(`A1:L${rows}`).format={font:{name:'Arial',size:12,color:'#193650'},rowHeight:27,verticalAlignment:'center'};s.getRange(`A1:A${rows}`).format.columnWidth=3;widths.forEach((a,i)=>s.getRange(`${C(i+2)}1:${C(i+2)}${rows}`).format.columnWidth=a);V(s,'B2',title);s.getRange('B2').format.font={size:18,bold:true};}
function head(s,row,arr){s.getRange(`B${row}:${C(arr.length+1)}${row}`).values=[arr];s.getRange(`B${row}:${C(arr.length+1)}${row}`).format={fill:'#193650',font:{color:'#FFFFFF',bold:true},wrapText:true,rowHeight:46,horizontalAlignment:'center'};}
function red(s,r){s.getRange(r).format.font={color:'#B52B2D',bold:true};s.getRange(r).format.borders={preset:'outside',style:'thin',color:'#B52B2D'};}
let s=sh.Sources;setup(s,'Dated inputs and saved simulation output',[42,22,22,22,22,22,22,24,24,24],110);head(s,5,['Quarterly financials ($m)','Apr–Jun 2025','Apr–Jun 2026']);s.getRange('B6:D10').values=fin.map(r=>[r.metric,r.prior,r.actual]);s.getRange('C6:D10').setNumberFormat(money);
head(s,13,['Frozen April 24 forecast','Forecast','Later actual']);s.getRange('B14:D19').values=prob.map(r=>[r.metric,r.forecast,r.actual]);s.getRange('C14:D19').setNumberFormat(pp);
head(s,22,['Saved simulation counts','Below −1pp','Within ±1pp','Above +1pp','Draws','P10','Median','P90']);s.getRange('B23:I28').values=count.map((r,i)=>[r.metric,r.below,r.near,r.above,r.draws,prob[i].p10,prob[i].median,prob[i].p90]);s.getRange('C23:F28').setNumberFormat('#,##0');s.getRange('G23:I28').setNumberFormat(pp);V(s,'B30','Counts are imported from a seeded 100,000-draw Python run. Rerun analysis to change simulation assumptions.');
head(s,33,['Historical error quarter',...prob.map(r=>r.metric)]);s.getRange('B34:H39').values=common.map(r=>[r.quarter,...prob.map(p=>r[p.metric])]);s.getRange('C34:H39').setNumberFormat(pp);s.getRange('C33:H33').format.rowHeight=70;
head(s,42,['Cost measure','Driver','Basis points']);s.getRange('B43:D52').values=cost.map(r=>[r.measure,r.driver,r.basis_points]);s.getRange('C43:C52').format.wrapText=true;s.getRange('B43:D52').format.rowHeight=42;
head(s,55,['US market YoY %','24-Apr forecast','1-Aug vintage']);s.getRange('B56:D59').values=market.map(r=>[r.series,r.forecast_growth,r.later_growth]);s.getRange('C56:D59').setNumberFormat(pp);
head(s,62,['Source ID','Published / period','Original link']);research.sources.forEach((r,i)=>{V(s,'B'+(63+i),r.id);V(s,'C'+(63+i),r.date);V(s,'D'+(63+i),r.url);});s.getRange('C63:C73').format.wrapText=true;s.getRange('B63:D73').format.rowHeight=42;
head(s,76,['Annual context ($m)','FY2025','FY2026']);s.getRange('B77:D78').values=[['Advertising costs',9200,10200],['Research and development',2100,2100]];s.getRange('C77:D78').setNumberFormat(money);V(s,'B80','Annual advertising is not quarterly advertising; SG&A reinvestment is not an advertising-only dollar figure.');
head(s,83,['Assumption','Value','Purpose']);s.getRange('B84:D86').values=[['Minimum error SD (pp)',config.sd_floor,'Analyst floor, tested against no floor'],['Student t degrees of freedom',config.df,'Heavy-tail assumption'],['Correlation shrinkage',config.correlation_shrinkage,'Reduce noisy historical correlation']];s.getRange('C84:C86').format.font={color:'#0000FF'};s.getRange('D84:D86').format.wrapText=true;s.getRange('B84:D86').format.rowHeight=42;s.freezePanes.freezeRows(5);
s=sh.Calculations;setup(s,'Financial bridges and historical error calibration',[42,22,22,22,22,22,22],75);head(s,5,['Quarterly financials ($m)','Prior year','Actual','Change','Change %']);fin.forEach((r,i)=>{let n=i+6;V(s,'B'+n,r.metric);F(s,'C'+n,`=Sources!C${n}`);F(s,'D'+n,`=Sources!D${n}`);F(s,'E'+n,`=D${n}-C${n}`);F(s,'F'+n,`=E${n}/C${n}`);});s.getRange('C6:E10').setNumberFormat(money);s.getRange('F6:F10').setNumberFormat('0.0%');
V(s,'B12','Operating income check: actual sales − COGS − SG&A − operating income');F(s,'C13','=D6-D7-D9-D10');V(s,'B15','Change bridge: sales change − COGS change − SG&A change');F(s,'C16','=E6-E7-E9');s.getRange('C16').setNumberFormat(money);
head(s,19,['Historical errors (pp)','Mean error','Historical SD','Used SD','Common quarters']);cal.forEach((r,i)=>{let n=20+i,col=C(3+i);V(s,'B'+n,r.metric);F(s,'C'+n,`=AVERAGE(Sources!${col}34:${col}39)`);F(s,'D'+n,`=STDEV(Sources!${col}34:${col}39)`);F(s,'E'+n,`=MAX(D${n},Sources!$C$84)`);F(s,'F'+n,`=COUNT(Sources!${col}34:${col}39)`);});s.getRange('C20:E25').setNumberFormat(pp);V(s,'B27','Used SD has a 1pp analyst floor. Historical errors alone are especially narrow for Health Care.');
head(s,30,['Simulation parameters (pp)','Frozen point','Historical bias','Simulation center','Used SD']);cal.forEach((r,i)=>{let n=31+i;V(s,'B'+n,r.metric);F(s,'C'+n,`=Sources!C${14+i}`);F(s,'D'+n,`=C${20+i}`);F(s,'E'+n,`=C${n}+D${n}`);F(s,'F'+n,`=E${20+i}`);});s.getRange('C31:F36').setNumberFormat(pp);V(s,'B38','Simulation = frozen point + mean historical error + correlated Student t shock × used SD.');V(s,'B39','Parameter formulas are live. Saved simulation probabilities require rerunning the Python analysis.');
head(s,42,['Market check (YoY %)','Forecast','Later data','Difference pp']);market.forEach((r,i)=>{let n=43+i;V(s,'B'+n,r.series);F(s,'C'+n,`=Sources!C${56+i}`);F(s,'D'+n,`=Sources!D${56+i}`);F(s,'E'+n,`=D${n}-C${n}`);});s.getRange('C43:E46').setNumberFormat(pp);
head(s,49,['Core cost bridge','Total bps']);V(s,'B50','Gross margin change');F(s,'C50','=SUM(Sources!D43:D49)');V(s,'B51','SG&A ratio change');F(s,'C51','=SUM(Sources!D50:D52)');V(s,'B53','Reported operating profit is GAAP. Core margin bridges exclude designated adjustments.');
s=sh.Review;setup(s,'P&G | Why did actual results differ?',[42,20,20,22,58],55);V(s,'B3','April–June 2026. Profit comparison is year-on-year; the sales reference is guidance-implied.');head(s,5,['Financial result ($m)','Prior year','Actual','Change']);fin.forEach((r,i)=>{let n=i+6;V(s,'B'+n,r.metric);for(let j=3;j<=5;j++)F(s,C(j)+n,`=Calculations!${C(j)}${n}`);});s.getRange('C6:E10').setNumberFormat(money);red(s,'E9:E10');V(s,'B12','Sales +$314m − extra product costs $289m − extra SG&A $431m = operating profit −$406m.');
head(s,15,['Forecast measure','Forecast','Actual','Difference pp','What the evidence supports']);research.causes.forEach((r,i)=>{let n=16+i;V(s,'B'+n,r.metric);V(s,'C'+n,r.forecast);V(s,'D'+n,r.actual);F(s,'E'+n,`=D${n}-C${n}`);V(s,'F'+n,r.interpretation);});s.getRange('B16:F21').format.wrapText=true;s.getRange('B16:F21').format.rowHeight=64;s.getRange('C16:E21').setNumberFormat(pp);red(s,'C16:E16');
head(s,24,['Cost explanation','Change bps','Meaning']);V(s,'B25','Core SG&A / sales');F(s,'C25','=Calculations!C51');V(s,'D25','Higher expense ratio');V(s,'B26','Core gross margin');F(s,'C26','=Calculations!C50');V(s,'D26','Savings offset cost pressure');V(s,'B28','The 410bps reinvestment is gross and mainly marketing. Productivity offsets 300bps.');V(s,'B29','No quarterly segment advertising ROI is available. Do not assign a causal percentage to advertising.');
head(s,32,['Annual advertising ($m)','FY2025','FY2026','Change']);V(s,'B33','Reported advertising expense');F(s,'C33','=Sources!C77');F(s,'D33','=Sources!D77');F(s,'E33','=D33-C33');s.getRange('C33:E33').setNumberFormat(money);V(s,'B35','Full-year context only. These costs cannot be allocated to this quarter or to a segment from public data.');
s=sh.Probabilities;setup(s,'P&G | Conditional outcome probabilities',[42,19,19,19,19,19,19],60);V(s,'B3','100,000 simulations; six common historical quarters; historical bias + 1pp minimum SD.');head(s,5,['Measure','Below >1pp','Within ±1pp','Above >1pp','P10','Median','P90']);count.forEach((r,i)=>{let n=6+i;V(s,'B'+n,r.metric);for(let j=3;j<=5;j++)F(s,C(j)+n,`=Sources!${C(j)}${23+i}/Sources!F${23+i}`);for(let j=6;j<=8;j++)F(s,C(j)+n,`=Sources!${C(j+1)}${23+i}`);});s.getRange('C6:E11').setNumberFormat('0%');s.getRange('F6:H11').setNumberFormat(pp);s.getRange('B6:H11').format.rowHeight=42;s.getRange('B6:B11').format.wrapText=true;V(s,'B13','Bands compare simulated outcomes with the original forecast; P10–P90 is an 80% model interval.');V(s,'B14','This describes possible results under assumptions, not the probability that a cause is true.');
head(s,17,['Assumption sensitivity','Measure','Below >1pp','Within ±1pp','Above >1pp']);let rr=18;for(const r of sens.filter(r=>['Beauty pricing','Health Care pricing'].includes(r.metric))){s.getRange(`B${rr}:F${rr}`).values=[[r.case,r.metric,r.below,r.near,r.above]];rr++;}s.getRange('D18:F25').setNumberFormat('0%');s.getRange('B18:C25').format.wrapText=true;s.getRange('B18:F25').format.rowHeight=40;
V(s,'B28','Health Care changes sharply when the SD floor is removed. Treat these probabilities as exploratory.');V(s,'B29','100,000 draws reduce sampling noise; they do not turn six quarters into a large historical dataset.');V(s,'B31','Rerun src/analyze_variance_causes.py to refresh simulations. Original point forecasts stay frozen.');
w.recalculate();function eq(a,b){if(typeof a!=='number'||Math.abs(a-b)>1e-8)throw Error(`${a} != ${b}`);}eq(sh.Calculations.getRange('C13').values[0][0],0);eq(sh.Calculations.getRange('C16').values[0][0],-406);eq(sh.Calculations.getRange('C50').values[0][0],0);eq(sh.Calculations.getRange('C51').values[0][0],130);cal.forEach((r,i)=>{eq(sh.Calculations.getRange('C'+(20+i)).values[0][0],r.bias);eq(sh.Calculations.getRange('E'+(20+i)).values[0][0],r.sd);eq(sh.Probabilities.getRange('C'+(6+i)).values[0][0],prob[i].below);});
V(sh.Sources,'D9',6335);w.recalculate();eq(sh.Review.getRange('E9').values[0][0],432);V(sh.Sources,'D9',6334);w.recalculate();
const out=root+'outputs/variance_causes';await fs.mkdir(out,{recursive:true});const check=(await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!',options:{useRegex:true,maxResults:20}})).ndjson;await fs.writeFile(out+'/formula_check.ndjson',check);await(await SpreadsheetFile.exportXlsx(w)).save(out+'/PG_9_Variance_Causes_and_Monte_Carlo.xlsx');
for(const [name,range] of [['Review','B2:E12'],['Probabilities','B2:H14'],['Calculations','B19:F27'],['Sources','B42:D52']]){await fs.writeFile(out+'/'+name+'.png',new Uint8Array(await(await w.render({sheetName:name,range,scale:1.5})).arrayBuffer()));}
await fs.writeFile(out+'/validation.json',JSON.stringify({financial_bridge:true,core_cost_bridge:true,simulation_counts_checked:true,calibration_matches_python:true,input_change_checked_and_restored:true},null,2));console.log('Workbook saved and checks passed.');
