import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=decodeURIComponent(new URL('../',import.meta.url).pathname),d=root+'data/jan_mar_replay/',o=root+'outputs/jan_mar_replay/';
const read=async n=>JSON.parse(await fs.readFile(d+n+'.json','utf8'));
const [c,p,s,input]=await Promise.all(['comparison','probabilities','summary','release_inputs'].map(read));
const w=Workbook.create(),sh=w.worksheets.add('Forecast review'),src=w.worksheets.add('Dated inputs');
const put=(s,r,v)=>s.getRange(r).values=[[v]],formula=(s,r,v)=>s.getRange(r).formulas=[[v]],fmt='0.00;[Red](0.00);"—"';
function setup(s){s.showGridLines=false;s.getRange('A1:I60').format={font:{name:'Arial',size:12,color:'#183A55'},rowHeight:28,verticalAlignment:'center'};s.getRange('A1:A60').format.columnWidth=3;s.getRange('B1:B60').format.columnWidth=41;s.getRange('C1:H60').format.columnWidth=17;}
function header(s,n,v){let r=s.getRange(`B${n}:${String.fromCharCode(66+v.length-1)}${n}`);r.values=[v];r.format={fill:'#183A55',font:{color:'#FFFFFF',bold:true},rowHeight:48,wrapText:true,horizontalAlignment:'center'};}
setup(sh);setup(src);put(sh,'B2','P&G Jan–Mar 2026: forecast review');sh.getRange('B2').format.font={size:18,bold:true};put(sh,'B3','Initial: 22 Jan. Update: 23 Apr. Actuals released: 24 Apr 2026.');
header(src,5,['Measure','22 Jan','23 Apr','Actual','Last actual','Four-quarter mean']);src.getRange('B6:G11').values=c.slice(0,6).map((r,i)=>[r.metric,r.forecast,c[i+6].forecast,r.actual,r.last,r.four]);src.getRange('C6:G11').setNumberFormat(fmt);src.getRange('C6:G11').format.font.color='#0000FF';src.getRange('B6:B11').format.wrapText=true;src.getRange('B6:G11').format.rowHeight=48;
put(src,'B2','Saved forecasts and dated market inputs');put(src,'B13','Model and simulation run in Python. Excel recalculates comparison errors.');
header(src,16,['Measure / stage','Cutoff','Vintage','Latest month','Observed months']);const ii=input.filter(x=>x.quarter==='2026-03-31');src.getRange('B17:F28').values=ii.map(x=>[x.metric+' / '+x.stage,new Date(x.cutoff),new Date(x.vintage),new Date(x.latest_market_month),x.target_months_observed]);src.getRange('B17:B28').format.wrapText=true;src.getRange('B17:F28').format.rowHeight=48;src.getRange('C17:E28').setNumberFormat('dd-mmm-yy');
put(src,'B31','Sources');put(src,'B32','Company actuals: Jan–Mar 2026 net sales drivers');put(src,'C33','https://www.pginvestor.com/news/news-details/2026/PG-Announces-Fiscal-Year-2026-Third-Quarter-Results/default.aspx');put(src,'B35','Pre-cutoff input audit and dated CSV links');put(src,'C36','https://github.com/hoichengit/Portfolio-Guide/blob/codex/pg-external-analysis/data/jan_mar_replay/release_inputs.csv');put(src,'B38','Simulation: 100,000 draws, Student t(5), 1pp scale floor.');put(src,'B39','Correlation shrunk 50% to zero. Only completed prior errors calibrate risk.');
header(sh,5,['Measure','22 Jan','23 Apr','Actual','Jan error','Apr error']);c.slice(0,6).forEach((r,i)=>{let n=i+6;put(sh,'B'+n,r.metric);for(const col of ['C','D','E'])formula(sh,col+n,`='Dated inputs'!${col}${n}`);formula(sh,'F'+n,`=ABS(C${n}-E${n})`);formula(sh,'G'+n,`=ABS(D${n}-E${n})`);});sh.getRange('B6:B11').format.wrapText=true;sh.getRange('B6:G11').format.rowHeight=48;sh.getRange('C6:G14').setNumberFormat(fmt);put(sh,'B13','Mean absolute error (pp)');formula(sh,'F13','=AVERAGE(F6:F11)');formula(sh,'G13','=AVERAGE(G6:G11)');sh.getRange('B13:G13').format.font.bold=true;sh.getRange('C6:G7').format.font.color='#B52B2D';
put(sh,'B15','Growth is %, pricing contribution is pp. Errors are percentage points.');put(sh,'B16','The update is less accurate. Four-quarter mean benchmark error: 2.63pp.');put(sh,'B17','Retrospective model design: this is not an untouched forecast test.');
header(sh,20,['23 Apr risk interval','Forecast','P10','P90','Within ±1pp','Actual']);sh.getRange('B21:G26').values=p.filter(x=>x.stage==='Pre-release').map(x=>[x.metric,x.forecast,x.p10,x.p90,x.near,x.actual]);sh.getRange('B21:B26').format.wrapText=true;sh.getRange('B21:G26').format.rowHeight=48;sh.getRange('C21:E26').setNumberFormat(fmt);sh.getRange('F21:F26').setNumberFormat('0.0%');sh.getRange('G21:G26').setNumberFormat(fmt);put(sh,'B28','Only 1 of 6 actual outcomes falls inside the updated 80% model intervals.');put(sh,'B29','These probabilities are conditional estimates; they are not reliable frequencies.');
header(sh,32,['Historical review','Initial','Pre-release']);sh.getRange('B33:D35').values=[['Mean absolute error (pp)',s[0].historical_mae,s[1].historical_mae],['Interval outcomes tested',s[0].interval_tests,s[1].interval_tests],['Observed interval coverage',s[0].interval_coverage,s[1].interval_coverage]];sh.getRange('C33:D33').setNumberFormat(fmt);sh.getRange('C35:D35').setNumberFormat('0.0%');put(sh,'B37','Some historical input gaps cause unequal samples; see the report.');
w.recalculate();for(let [cell,value] of [['F13',s[0].target_mae],['G13',s[1].target_mae]])if(Math.abs(sh.getRange(cell).values[0][0]-value)>1e-9)throw Error('MAE mismatch');
await(await SpreadsheetFile.exportXlsx(w)).save(o+'PG_12_Jan_Mar_Replay.xlsx');
for(const [range,file] of [['B2:G17','Review'],['B20:G29','Simulation']])await fs.writeFile(o+file+'.png',new Uint8Array(await(await w.render({sheetName:'Forecast review',range,scale:1.5})).arrayBuffer()));
await fs.writeFile(o+'formula_check.ndjson',(await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!',options:{useRegex:true,maxResults:20}})).ndjson);console.log('Exported and verified.');
