"""Read-only verification of source inputs, saved workbook values and report links."""
from pathlib import Path
import csv,json,re,hashlib
import openpyxl
R=Path(__file__).resolve().parents[1]
source=openpyxl.load_workbook(R/'raw_data/PG_2026_Company_Financials.xlsx',data_only=True)
w=openpyxl.load_workbook(R/'outputs/PG_1_Analysis.xlsx',data_only=True)
n=0
normal=lambda v:0 if isinstance(v,str) and v.strip()=='—' else v
for index,row in enumerate(json.loads((R/'processed_data/financial_history.json').read_text())):
 for y,v,sc,dc in zip([2024,2025,2026],row['values'],[6,4,2],[3,4,5]):
  assert normal(source.worksheets[0].cell(row['company_excel_row'],sc).value)==v
  assert w['Reported Earnings'].cell(index+7,dc).value==v
  n+=1
extended=json.loads((R/'processed_data/extended_history.json').read_text())
for kind,sheet,scs in [('balance_sheet','Reported Balance',[4,2]),('cash_flow','Reported Cash',[6,4,2])]:
 for index,row in enumerate(extended[kind]):
  for j,(v,sc) in enumerate(zip(row['values'],scs)):
   assert normal(source[row['source_sheet']].cell(row['source_row'],sc).value)==v
   assert w[sheet].cell(index+7,j+3).value==v
   n+=1
assert n==199,n
assert w['PG_1_Analysis']['F7'].value==2748
assert w['PG_1_Analysis']['F12'].value==-703
assert sum(x[2]-x[1] for x in extended['segments'])==2748
assert sum(x[1] for x in extended['gross_margin_drivers'])==-100
errors=[f'{s.title}!{c.coordinate}' for s in w for row in s for c in row if c.data_type=='e']
assert not errors,errors
# Check links in report pages only; old raw PDF downloads can legitimately be external.
files=[R/'README.md',R/'SKILLS.md']
for folder in ['analysis','agents','data','model','dashboard','reports','decisions','qa']:
 files.extend((R/folder).rglob('*.md'))
missing=[]
for p in files:
 for pair in re.findall(r'\]\(([^)]+)\)|(?:src|href)="([^"]+)"',p.read_text()):
  target=next(x for x in pair if x)
  if target.startswith(('https://','http://','#')):continue
  resolved=(p.parent/target.split('#')[0]).resolve()
  if resolved==(R/'qa/portfolio_validation.json').resolve():continue  # generated by this successful verification
  if not resolved.exists():missing.append((str(p.relative_to(R)),target))
assert not missing,missing
result={'status':'passed','reported_inputs_matched_to_source_and_workbook':n,'saved_workbook_error_cells':len(errors),'report_pages_checked':len(files),'missing_local_links':len(missing),'headline_checks':['revenue change +2748','operating income change -703','segment increases +2748','company gross margin bridge -100 bps'],'workbook_sha256':hashlib.sha256((R/'outputs/PG_1_Analysis.xlsx').read_bytes()).hexdigest(),'scope':'Read-only source comparison and saved-result checks; not a new Excel recalculation or audit.'}
(R/'qa').mkdir(exist_ok=True)
(R/'qa/portfolio_validation.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps(result))
